import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar, generated from ../docs. Order and labels come from each page's
// front matter (sidebar_position, title) once the docs carry it.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
