/**
 * THE GLYPH CATALOG — R5b (STA-182).
 *
 * A lookup over every icon the installed `lucide-react` ships, generated by
 * `npx tsx scripts/gen-lucide-catalog.ts` into the two `*.generated.ts` modules next
 * to this file. This module is the surface the rest of the app consumes:
 *
 *   - `resolveIcon(key)` — the key STA-181 persists on a kind is a CANONICAL Lucide
 *     name (`triangle-alert`). Aliases (`alert-triangle`) and sloppy input
 *     ("Triangle Alert") resolve to the same entry; anything unknown is `undefined`,
 *     which is the caller's cue to fall back rather than render nothing.
 *   - `searchIcons(query)` — what the settings picker (STA-184) types into. Ranked,
 *     deterministic, over names, alias words, and an optional category filter.
 *   - `loadIconComponent(key)` — the only path to a React component. It goes through
 *     `import()` so the module that names every icon becomes its own chunk and the
 *     main view never pays for icons it does not draw.
 *
 * The manifest itself is data only (no icon code) and stores just category and
 * aliases per key; labels, search terms, and the alias map are rebuilt here at load,
 * so importing this module costs the manifest and nothing else.
 */
import type { LucideIcon } from "lucide-react";
import { ICON_CATEGORIES, ICON_MANIFEST, LUCIDE_VERSION, type IconCategory, type IconKey } from "./icon-catalog.generated";

export type { IconCategory, IconKey };
export { ICON_CATEGORIES, LUCIDE_VERSION };

export interface IconCatalogEntry {
  /** Canonical Lucide name — the value to persist. */
  readonly key: IconKey;
  /** Human label: "Triangle Alert". */
  readonly label: string;
  /** Lowercase search words from the key and its aliases, sorted and unique. */
  readonly terms: readonly string[];
  readonly category: IconCategory;
  /** Lucide's other names for this icon (`alert-triangle` on `triangle-alert`). Never keys. */
  readonly aliases: readonly string[];
}

export interface IconSearchOptions {
  readonly category?: IconCategory;
  readonly limit?: number;
}

interface IndexedEntry {
  readonly entry: IconCatalogEntry;
  readonly words: readonly string[];
}

const words = (key: string): string[] => key.split("-");

/** `triangle-alert` → "Triangle Alert". */
export function iconLabel(key: string): string {
  return words(key)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

const INDEX: readonly IndexedEntry[] = (Object.keys(ICON_MANIFEST) as IconKey[]).map((key) => {
  const [category, ...aliases] = ICON_MANIFEST[key];
  const keyWords = words(key);
  const terms = [...new Set([...keyWords, ...aliases.flatMap(words)])].sort();
  return { entry: { key, label: iconLabel(key), terms, category, aliases }, words: keyWords };
});

const ENTRIES: readonly IconCatalogEntry[] = INDEX.map((indexed) => indexed.entry);

const BY_KEY = new Map<string, IconCatalogEntry>(ENTRIES.map((entry) => [entry.key, entry]));

/** Alias → canonical key, derived from the manifest. */
export const ICON_ALIASES: Readonly<Record<string, IconKey>> = Object.fromEntries(
  ENTRIES.flatMap((entry) => entry.aliases.map((alias) => [alias, entry.key] as const)),
);

/** Every canonical entry, in key order. */
export function iconCatalog(): readonly IconCatalogEntry[] {
  return ENTRIES;
}

/** Trim, lowercase, and turn whitespace or underscores into the kebab dash Lucide uses. */
export function normalizeIconKey(input: string): string {
  return input.trim().toLowerCase().replace(/[\s_]+/g, "-");
}

export function isIconKey(value: string): value is IconKey {
  return BY_KEY.has(value);
}

/** Canonical key, alias, or loosely typed name → the canonical entry; unknown → `undefined`. */
export function resolveIcon(key: string): IconCatalogEntry | undefined {
  const normalized = normalizeIconKey(key);
  const direct = BY_KEY.get(normalized);
  if (direct !== undefined) return direct;
  const canonical = ICON_ALIASES[normalized];
  return canonical === undefined ? undefined : BY_KEY.get(canonical);
}

/**
 * Lower is better. `undefined` means no match.
 *   0  the whole query is this icon's key or one of its aliases
 *   1  every query word is a whole word of the key
 *   2  every query word starts a word of the key
 *   3  every query word starts a search term (alias words included)
 *   4  every query word occurs somewhere in the key or a term
 */
function rankOf(indexed: IndexedEntry, words: readonly string[], exact: IconCatalogEntry | undefined): number | undefined {
  if (exact !== undefined && exact.key === indexed.entry.key) return 0;
  const { entry, words: keyWords } = indexed;
  if (words.every((word) => keyWords.includes(word))) return 1;
  if (words.every((word) => keyWords.some((keyWord) => keyWord.startsWith(word)))) return 2;
  if (words.every((word) => entry.terms.some((term) => term.startsWith(word)))) return 3;
  if (words.every((word) => entry.key.includes(word) || entry.terms.some((term) => term.includes(word)))) return 4;
  return undefined;
}

/**
 * Ranked search. Ties break on fewer key words (the plainer icon first), then key
 * order, so the same query always yields the same list. An empty query lists the
 * catalog (optionally one category) in key order.
 */
export function searchIcons(query: string, options: IconSearchOptions = {}): IconCatalogEntry[] {
  const pool = options.category === undefined ? INDEX : INDEX.filter((indexed) => indexed.entry.category === options.category);
  const limit = options.limit ?? pool.length;
  const words = normalizeIconKey(query).split("-").filter((word) => word.length > 0);
  if (words.length === 0) return pool.slice(0, limit).map((indexed) => indexed.entry);
  const exact = resolveIcon(words.join("-"));
  const ranked: { indexed: IndexedEntry; rank: number; order: number }[] = [];
  pool.forEach((indexed, order) => {
    const rank = rankOf(indexed, words, exact);
    if (rank !== undefined) ranked.push({ indexed, rank, order });
  });
  ranked.sort((a, b) => a.rank - b.rank || a.indexed.words.length - b.indexed.words.length || a.order - b.order);
  return ranked.slice(0, limit).map((hit) => hit.indexed.entry);
}

/** The full key → component map, loaded once as its own chunk. For pickers that preview many icons. */
export async function loadIconComponents(): Promise<Readonly<Record<IconKey, LucideIcon>>> {
  const { ICON_COMPONENTS } = await import("./icon-previews.generated");
  return ICON_COMPONENTS;
}

/** One icon's component, alias-aware; `undefined` when the key resolves to nothing. */
export async function loadIconComponent(key: string): Promise<LucideIcon | undefined> {
  const entry = resolveIcon(key);
  if (entry === undefined) return undefined;
  const components = await loadIconComponents();
  return components[entry.key];
}
