/**
 * GENERATED — do not edit by hand.
 * Regenerate with: npx tsx scripts/gen-lucide-catalog.ts
 *
 * Preview components for lucide-react 1.39.0: 1792 canonical icons,
 * 258 aliases collapsed onto them.
 *
 * Only ever reach this module through `import()` (see `loadIconComponent` in
 * icon-catalog.ts): it names every icon, so wherever it is imported statically,
 * every icon ships. A missing export here fails typecheck and build — that is
 * the proof that every catalog key resolves to a bundled icon.
 */
import {
  AArrowDown,
  AArrowUp,
  ALargeSmall,
  Accessibility,
  Activity,
  Ad,
  AirVent,
  Airplay,
  AlarmClock,
  AlarmClockCheck,
  AlarmClockMinus,
  AlarmClockOff,
  AlarmClockPlus,
  AlarmSmoke,
  Album,
  AlignCenterHorizontal,
  AlignCenterVertical,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignHorizontalDistributeCenter,
  AlignHorizontalDistributeEnd,
  AlignHorizontalDistributeStart,
  AlignHorizontalJustifyCenter,
  AlignHorizontalJustifyEnd,
  AlignHorizontalJustifyStart,
  AlignHorizontalSpaceAround,
  AlignHorizontalSpaceBetween,
  AlignStartHorizontal,
  AlignStartVertical,
  AlignVerticalDistributeCenter,
  AlignVerticalDistributeEnd,
  AlignVerticalDistributeStart,
  AlignVerticalJustifyCenter,
  AlignVerticalJustifyEnd,
  AlignVerticalJustifyStart,
  AlignVerticalSpaceAround,
  AlignVerticalSpaceBetween,
  Ambulance,
  Ampersand,
  Ampersands,
  Amphora,
  Anchor,
  Angle,
  Antenna,
  Anvil,
  Aperture,
  AppWindow,
  AppWindowMac,
  Apple,
  Archive,
  ArchiveRestore,
  ArchiveX,
  Armchair,
  ArrowBigDown,
  ArrowBigDownDash,
  ArrowBigLeft,
  ArrowBigLeftDash,
  ArrowBigRight,
  ArrowBigRightDash,
  ArrowBigUp,
  ArrowBigUpDash,
  ArrowDown,
  ArrowDown01,
  ArrowDown10,
  ArrowDownAZ,
  ArrowDownFromLine,
  ArrowDownLeft,
  ArrowDownNarrowWide,
  ArrowDownRight,
  ArrowDownToDot,
  ArrowDownToLine,
  ArrowDownUp,
  ArrowDownWideNarrow,
  ArrowDownZA,
  ArrowLeft,
  ArrowLeftFromLine,
  ArrowLeftRight,
  ArrowLeftToLine,
  ArrowRight,
  ArrowRightFromLine,
  ArrowRightLeft,
  ArrowRightToLine,
  ArrowUp,
  ArrowUp01,
  ArrowUp10,
  ArrowUpAZ,
  ArrowUpDown,
  ArrowUpFromDot,
  ArrowUpFromLine,
  ArrowUpLeft,
  ArrowUpNarrowWide,
  ArrowUpRight,
  ArrowUpToLine,
  ArrowUpWideNarrow,
  ArrowUpZA,
  ArrowsUpFromLine,
  Asterisk,
  Astroid,
  AtSign,
  Atom,
  AudioLines,
  AudioLinesOff,
  AudioLinesX,
  AudioWaveform,
  Award,
  Axe,
  Axis3d,
  Baby,
  Backpack,
  Badge,
  BadgeAlert,
  BadgeCent,
  BadgeCheck,
  BadgeDollarSign,
  BadgeEuro,
  BadgeIndianRupee,
  BadgeInfo,
  BadgeJapaneseYen,
  BadgeMinus,
  BadgePercent,
  BadgePlus,
  BadgePoundSterling,
  BadgeQuestionMark,
  BadgeRussianRuble,
  BadgeSwissFranc,
  BadgeTurkishLira,
  BadgeX,
  BaggageClaim,
  Balloon,
  Ban,
  Banana,
  Bandage,
  Banknote,
  BanknoteArrowDown,
  BanknoteArrowUp,
  BanknoteCheck,
  BanknoteX,
  Barcode,
  Barrel,
  Baseline,
  Bath,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  BatteryPlus,
  BatteryWarning,
  Beaker,
  Bean,
  BeanOff,
  Bed,
  BedDouble,
  BedSingle,
  Beef,
  BeefOff,
  Beer,
  BeerOff,
  Bell,
  BellCheck,
  BellDot,
  BellElectric,
  BellMinus,
  BellOff,
  BellPlus,
  BellRing,
  BetweenHorizontalEnd,
  BetweenHorizontalStart,
  BetweenVerticalEnd,
  BetweenVerticalStart,
  BicepsFlexed,
  Bike,
  Binary,
  Binoculars,
  Biohazard,
  Bird,
  Birdhouse,
  Bitcoin,
  Blend,
  Blender,
  Blinds,
  Blocks,
  Bluetooth,
  BluetoothConnected,
  BluetoothOff,
  BluetoothSearching,
  Bold,
  Bolt,
  Bomb,
  Bone,
  BoneFracture,
  Book,
  BookA,
  BookAlert,
  BookAudio,
  BookCheck,
  BookCopy,
  BookDashed,
  BookDown,
  BookHeadphones,
  BookHeart,
  BookImage,
  BookKey,
  BookLock,
  BookMarked,
  BookMinus,
  BookOpen,
  BookOpenCheck,
  BookOpenText,
  BookPlus,
  BookSearch,
  BookText,
  BookType,
  BookUp,
  BookUp2,
  BookUser,
  BookX,
  Bookmark,
  BookmarkCheck,
  BookmarkMinus,
  BookmarkOff,
  BookmarkPlus,
  BookmarkX,
  BoomBox,
  Bot,
  BotMessageSquare,
  BotOff,
  BottleWine,
  BowArrow,
  Box,
  Boxes,
  Braces,
  Brackets,
  Brain,
  BrainCircuit,
  BrainCog,
  BrickWall,
  BrickWallFire,
  BrickWallShield,
  Briefcase,
  BriefcaseBusiness,
  BriefcaseConveyorBelt,
  BriefcaseMedical,
  BringToFront,
  Broccoli,
  Broom,
  BroomSparkles,
  Brush,
  BrushCleaning,
  Bubbles,
  Bug,
  BugOff,
  BugPlay,
  Building,
  Building2,
  Bus,
  BusFront,
  Cable,
  CableCar,
  Cake,
  CakeSlice,
  Calculator,
  Calendar,
  Calendar1,
  CalendarArrowDown,
  CalendarArrowUp,
  CalendarCheck,
  CalendarCheck2,
  CalendarClock,
  CalendarCog,
  CalendarDays,
  CalendarFold,
  CalendarHeart,
  CalendarMinus,
  CalendarMinus2,
  CalendarOff,
  CalendarPlus,
  CalendarPlus2,
  CalendarRange,
  CalendarSearch,
  CalendarSync,
  CalendarX,
  CalendarX2,
  Calendars,
  Camera,
  CameraOff,
  Candy,
  CandyCane,
  CandyOff,
  Cannabis,
  CannabisOff,
  Captions,
  CaptionsOff,
  Car,
  CarBattery,
  CarFront,
  CarTaxiFront,
  Caravan,
  CardSim,
  Carrot,
  CaseLower,
  CaseSensitive,
  CaseUpper,
  CassetteTape,
  Cast,
  Castle,
  Cat,
  Cctv,
  CctvOff,
  ChartArea,
  ChartBar,
  ChartBarBig,
  ChartBarDecreasing,
  ChartBarIncreasing,
  ChartBarStacked,
  ChartCandlestick,
  ChartColumn,
  ChartColumnBig,
  ChartColumnDecreasing,
  ChartColumnIncreasing,
  ChartColumnStacked,
  ChartGantt,
  ChartLine,
  ChartNetwork,
  ChartNoAxesColumn,
  ChartNoAxesColumnDecreasing,
  ChartNoAxesColumnIncreasing,
  ChartNoAxesCombined,
  ChartNoAxesGantt,
  ChartPie,
  ChartScatter,
  ChartSpline,
  Check,
  CheckCheck,
  CheckLine,
  ChefHat,
  Cherry,
  ChessBishop,
  ChessKing,
  ChessKnight,
  ChessPawn,
  ChessQueen,
  ChessRook,
  ChevronDown,
  ChevronFirst,
  ChevronLast,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsDownUp,
  ChevronsLeft,
  ChevronsLeftRight,
  ChevronsLeftRightEllipsis,
  ChevronsRight,
  ChevronsRightLeft,
  ChevronsUp,
  ChevronsUpDown,
  Church,
  Cigarette,
  CigaretteOff,
  Circle,
  CircleAlert,
  CircleArrowDown,
  CircleArrowLeft,
  CircleArrowOutDownLeft,
  CircleArrowOutDownRight,
  CircleArrowOutUpLeft,
  CircleArrowOutUpRight,
  CircleArrowRight,
  CircleArrowUp,
  CircleCheck,
  CircleCheckBig,
  CircleChevronDown,
  CircleChevronLeft,
  CircleChevronRight,
  CircleChevronUp,
  CircleDashed,
  CircleDivide,
  CircleDollarSign,
  CircleDot,
  CircleDotDashed,
  CircleEllipsis,
  CircleEqual,
  CircleEuro,
  CircleFadingArrowUp,
  CircleFadingPlus,
  CircleGauge,
  CircleMinus,
  CircleOff,
  CircleParking,
  CircleParkingOff,
  CirclePause,
  CirclePercent,
  CirclePile,
  CirclePlay,
  CirclePlus,
  CirclePoundSterling,
  CirclePower,
  CircleQuestionMark,
  CircleSlash,
  CircleSlash2,
  CircleSmall,
  CircleStar,
  CircleStop,
  CircleUser,
  CircleUserRound,
  CircleX,
  CircuitBoard,
  Citrus,
  Clapperboard,
  Clipboard,
  ClipboardCheck,
  ClipboardClock,
  ClipboardCopy,
  ClipboardList,
  ClipboardMinus,
  ClipboardPaste,
  ClipboardPen,
  ClipboardPenLine,
  ClipboardPlus,
  ClipboardType,
  ClipboardX,
  Clock,
  Clock1,
  Clock10,
  Clock11,
  Clock12,
  Clock2,
  Clock3,
  Clock4,
  Clock5,
  Clock6,
  Clock7,
  Clock8,
  Clock9,
  ClockAlert,
  ClockArrowDown,
  ClockArrowLeft,
  ClockArrowRight,
  ClockArrowUp,
  ClockCheck,
  ClockFading,
  ClockPlus,
  ClosedCaption,
  Cloud,
  CloudAlert,
  CloudBackup,
  CloudCheck,
  CloudCog,
  CloudDownload,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudMoonRain,
  CloudOff,
  CloudRain,
  CloudRainWind,
  CloudSnow,
  CloudSun,
  CloudSunRain,
  CloudSync,
  CloudUpload,
  Cloudy,
  Clover,
  Club,
  Code,
  CodeXml,
  Coffee,
  Cog,
  Coins,
  Columns2,
  Columns3,
  Columns3Cog,
  Columns4,
  Combine,
  Command,
  Compass,
  Component,
  Computer,
  ConciergeBell,
  Cone,
  Construction,
  Contact,
  ContactRound,
  Container,
  Contrast,
  Cookie,
  CookingPot,
  Copy,
  CopyCheck,
  CopyMinus,
  CopyPlus,
  CopySlash,
  CopyX,
  Copyleft,
  Copyright,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreativeCommons,
  CreditCard,
  CreditCardCheck,
  CreditCardMinus,
  CreditCardPlus,
  CreditCardX,
  Croissant,
  Crop,
  Cross,
  Crosshair,
  Crown,
  Cuboid,
  CupSoda,
  Currency,
  Cylinder,
  Dam,
  Database,
  DatabaseArrowDown,
  DatabaseArrowUp,
  DatabaseBackup,
  DatabaseCheck,
  DatabaseMinus,
  DatabasePlus,
  DatabaseSearch,
  DatabaseX,
  DatabaseZap,
  DecimalsArrowLeft,
  DecimalsArrowRight,
  Delete,
  Dessert,
  Diameter,
  Diamond,
  DiamondMinus,
  DiamondPercent,
  DiamondPlus,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Dices,
  Diff,
  Disc,
  Disc2,
  Disc3,
  DiscAlbum,
  Divide,
  Dna,
  DnaOff,
  Dock,
  Dog,
  DollarSign,
  Donut,
  DoorClosed,
  DoorClosedLocked,
  DoorOpen,
  Dot,
  Download,
  DraftingCompass,
  Drama,
  Drill,
  Drone,
  Droplet,
  DropletOff,
  Droplets,
  Drum,
  Drumstick,
  Dumbbell,
  Ear,
  EarOff,
  Earth,
  EarthLock,
  Eclipse,
  Egg,
  EggFried,
  EggOff,
  Eject,
  Ellipse,
  Ellipsis,
  EllipsisVertical,
  Equal,
  EqualApproximately,
  EqualNot,
  Eraser,
  EthernetPort,
  Euro,
  EvCharger,
  Expand,
  ExternalLink,
  Eye,
  EyeClosed,
  EyeDashed,
  EyeOff,
  FaceAngry,
  FaceExpressionless,
  FaceGrinning,
  FaceNeutral,
  FaceSlightlyFrowning,
  FaceSlightlySmiling,
  FaceSlightlySmilingPlus,
  Factory,
  Fan,
  FastForward,
  Feather,
  Fence,
  FerrisWheel,
  File,
  FileArchive,
  FileAxis3d,
  FileBadge,
  FileBox,
  FileBraces,
  FileBracesCorner,
  FileChartColumn,
  FileChartColumnIncreasing,
  FileChartLine,
  FileChartPie,
  FileCheck,
  FileCheckCorner,
  FileClock,
  FileCode,
  FileCodeCorner,
  FileCog,
  FileDiff,
  FileDigit,
  FileDown,
  FileExclamationPoint,
  FileHeadphone,
  FileHeart,
  FileImage,
  FileInput,
  FileKey,
  FileLock,
  FileMinus,
  FileMinusCorner,
  FileMusic,
  FileOutput,
  FilePen,
  FilePenLine,
  FilePlay,
  FilePlus,
  FilePlusCorner,
  FileQuestionMark,
  FileScan,
  FileSearch,
  FileSearchCorner,
  FileSignal,
  FileSliders,
  FileSpreadsheet,
  FileStack,
  FileSymlink,
  FileTerminal,
  FileText,
  FileType,
  FileTypeCorner,
  FileUp,
  FileUser,
  FileVideoCamera,
  FileVolume,
  FileX,
  FileXCorner,
  Files,
  Film,
  FingerprintPattern,
  FireExtinguisher,
  Fish,
  FishOff,
  FishSymbol,
  FishingHook,
  FishingRod,
  Flag,
  FlagOff,
  FlagTriangleLeft,
  FlagTriangleRight,
  Flame,
  FlameKindling,
  Flashlight,
  FlashlightOff,
  FlaskConical,
  FlaskConicalOff,
  FlaskRound,
  FlipHorizontal2,
  FlipVertical2,
  Flower,
  Flower2,
  Focus,
  FoldHorizontal,
  FoldVertical,
  Folder,
  FolderArchive,
  FolderBookmark,
  FolderCheck,
  FolderClock,
  FolderClosed,
  FolderCode,
  FolderCog,
  FolderDot,
  FolderDown,
  FolderGit,
  FolderGit2,
  FolderHeart,
  FolderInput,
  FolderKanban,
  FolderKey,
  FolderLock,
  FolderMinus,
  FolderOpen,
  FolderOpenDot,
  FolderOutput,
  FolderPen,
  FolderPlus,
  FolderRoot,
  FolderSearch,
  FolderSearch2,
  FolderSymlink,
  FolderSync,
  FolderTree,
  FolderUp,
  FolderX,
  Folders,
  Footprints,
  Forklift,
  Form,
  Forward,
  Frame,
  Fuel,
  Fullscreen,
  Funnel,
  FunnelPlus,
  FunnelX,
  Galaxy,
  GalleryHorizontal,
  GalleryHorizontalEnd,
  GalleryThumbnails,
  GalleryVertical,
  GalleryVerticalEnd,
  Gamepad,
  Gamepad2,
  GamepadDirectional,
  Gauge,
  Gavel,
  Gem,
  GeorgianLari,
  Ghost,
  Gift,
  GitBranch,
  GitBranchMinus,
  GitBranchPlus,
  GitCommitHorizontal,
  GitCommitVertical,
  GitCompare,
  GitCompareArrows,
  GitFork,
  GitGraph,
  GitMerge,
  GitMergeConflict,
  GitPullRequest,
  GitPullRequestArrow,
  GitPullRequestClosed,
  GitPullRequestCreate,
  GitPullRequestCreateArrow,
  GitPullRequestDraft,
  GlassWater,
  Glasses,
  Globe,
  GlobeCheck,
  GlobeLock,
  GlobeOff,
  GlobeX,
  Goal,
  Gpu,
  GraduationCap,
  Grape,
  Grid2x2,
  Grid2x2Check,
  Grid2x2Plus,
  Grid2x2X,
  Grid3x2,
  Grid3x3,
  Grip,
  GripHorizontal,
  GripVertical,
  Group,
  Guitar,
  Ham,
  Hamburger,
  Hammer,
  Hand,
  HandCoins,
  HandFist,
  HandGrab,
  HandHeart,
  HandHelping,
  HandMetal,
  HandPlatter,
  Handbag,
  Handshake,
  HardDrive,
  HardDriveDownload,
  HardDriveUpload,
  HardHat,
  Hash,
  HatGlasses,
  Haze,
  Hd,
  HdmiPort,
  Heading,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  HeadphoneOff,
  Headphones,
  Headset,
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartMinus,
  HeartOff,
  HeartPlus,
  HeartPulse,
  HeartX,
  Heater,
  Helicopter,
  Hexagon,
  Highlighter,
  Hop,
  HopOff,
  Hospital,
  Hotel,
  Hourglass,
  House,
  HouseHeart,
  HousePlug,
  HousePlus,
  HouseWifi,
  IceCreamBowl,
  IceCreamCone,
  IdCard,
  IdCardLanyard,
  Image,
  ImageDown,
  ImageMinus,
  ImageOff,
  ImagePlay,
  ImagePlus,
  ImageUp,
  ImageUpscale,
  Images,
  Import,
  Inbox,
  IndianRupee,
  Infinity,
  Info,
  InspectionPanel,
  Italic,
  IterationCcw,
  IterationCw,
  JapaneseYen,
  Joystick,
  Kanban,
  Kayak,
  Key,
  KeyRound,
  KeySquare,
  Keyboard,
  KeyboardMusic,
  KeyboardOff,
  Lamp,
  LampCeiling,
  LampDesk,
  LampFloor,
  LampWallDown,
  LampWallUp,
  LandPlot,
  Landmark,
  Languages,
  Laptop,
  LaptopMinimal,
  LaptopMinimalCheck,
  Lasso,
  LassoSelect,
  LayerArrowDown,
  LayerArrowUp,
  Layers,
  Layers2,
  LayersArrowDown,
  LayersArrowUp,
  LayersMinus,
  LayersPlus,
  LayoutDashboard,
  LayoutFreeform,
  LayoutGrid,
  LayoutList,
  LayoutPanelLeft,
  LayoutPanelTop,
  LayoutTemplate,
  Leaf,
  LeafyGreen,
  Lectern,
  LensConcave,
  LensConvex,
  Library,
  LibraryBig,
  LifeBuoy,
  Ligature,
  Lightbulb,
  LightbulbOff,
  LineDotRightHorizontal,
  LineSquiggle,
  LineStyle,
  Link,
  Link2,
  Link2Off,
  List,
  ListCheck,
  ListChecks,
  ListChevronsDownUp,
  ListChevronsUpDown,
  ListClock,
  ListCollapse,
  ListEnd,
  ListFilter,
  ListFilterPlus,
  ListIndentDecrease,
  ListIndentIncrease,
  ListMinus,
  ListMusic,
  ListOrdered,
  ListPlus,
  ListRestart,
  ListSortAscending,
  ListSortDescending,
  ListStart,
  ListTodo,
  ListTree,
  ListVideo,
  ListX,
  Loader,
  LoaderCircle,
  LoaderPinwheel,
  Locate,
  LocateFixed,
  LocateOff,
  Lock,
  LockKeyhole,
  LockKeyholeOpen,
  LockOpen,
  LogIn,
  LogOut,
  Logs,
  Lollipop,
  Luggage,
  Magnet,
  Mail,
  MailBadge,
  MailCheck,
  MailClock,
  MailMinus,
  MailOpen,
  MailPlus,
  MailQuestionMark,
  MailSearch,
  MailWarning,
  MailX,
  Mailbox,
  Mails,
  Map,
  MapMinus,
  MapPin,
  MapPinCheck,
  MapPinCheckInside,
  MapPinHouse,
  MapPinMinus,
  MapPinMinusInside,
  MapPinOff,
  MapPinPen,
  MapPinPlus,
  MapPinPlusInside,
  MapPinSearch,
  MapPinX,
  MapPinXInside,
  MapPinned,
  MapPlus,
  Mars,
  MarsStroke,
  Martini,
  Maximize,
  Maximize2,
  Medal,
  Megaphone,
  MegaphoneOff,
  MemoryStick,
  Menu,
  Merge,
  MessageCircle,
  MessageCircleCheck,
  MessageCircleCode,
  MessageCircleDashed,
  MessageCircleDashedCheck,
  MessageCircleHeart,
  MessageCircleMore,
  MessageCircleOff,
  MessageCirclePlus,
  MessageCircleQuestionMark,
  MessageCircleReply,
  MessageCircleWarning,
  MessageCircleX,
  MessageSquare,
  MessageSquareCheck,
  MessageSquareCode,
  MessageSquareDashed,
  MessageSquareDiff,
  MessageSquareDot,
  MessageSquareHeart,
  MessageSquareLock,
  MessageSquareMore,
  MessageSquareOff,
  MessageSquarePlus,
  MessageSquareQuote,
  MessageSquareReply,
  MessageSquareShare,
  MessageSquareText,
  MessageSquareWarning,
  MessageSquareX,
  MessagesSquare,
  Metronome,
  Mic,
  MicAudioLines,
  MicOff,
  MicSignal,
  MicVocal,
  Microchip,
  Microscope,
  Microwave,
  MidiPort,
  Milestone,
  Milk,
  MilkOff,
  Minimize,
  Minimize2,
  Minus,
  MirrorRectangular,
  MirrorRound,
  Monitor,
  MonitorCheck,
  MonitorCloud,
  MonitorCog,
  MonitorDot,
  MonitorDown,
  MonitorOff,
  MonitorPause,
  MonitorPlay,
  MonitorSmartphone,
  MonitorSpeaker,
  MonitorStop,
  MonitorUp,
  MonitorX,
  Moon,
  MoonStar,
  Mop,
  MopSparkles,
  Mosque,
  Motorbike,
  Mountain,
  MountainSnow,
  Mouse,
  MouseLeft,
  MouseOff,
  MousePointer,
  MousePointer2,
  MousePointer2Off,
  MousePointerBan,
  MousePointerClick,
  MouseRight,
  Move,
  Move3d,
  MoveDiagonal,
  MoveDiagonal2,
  MoveDown,
  MoveDownLeft,
  MoveDownRight,
  MoveHorizontal,
  MoveLeft,
  MoveRight,
  MoveUp,
  MoveUpLeft,
  MoveUpRight,
  MoveVertical,
  Music,
  Music2,
  Music3,
  Music4,
  Navigation,
  Navigation2,
  Navigation2Off,
  NavigationOff,
  Network,
  Newspaper,
  Nfc,
  NonBinary,
  Notebook,
  NotebookPen,
  NotebookTabs,
  NotebookText,
  NotepadText,
  NotepadTextDashed,
  Nut,
  NutOff,
  Octagon,
  OctagonAlert,
  OctagonMinus,
  OctagonPause,
  OctagonX,
  Omega,
  Option,
  Orbit,
  Origami,
  Package,
  Package2,
  PackageCheck,
  PackageMinus,
  PackageOpen,
  PackagePlus,
  PackageSearch,
  PackageX,
  PaintBucket,
  PaintRoller,
  Paintbrush,
  PaintbrushVertical,
  Palette,
  Panda,
  PanelBottom,
  PanelBottomClose,
  PanelBottomDashed,
  PanelBottomOpen,
  PanelLeft,
  PanelLeftClose,
  PanelLeftDashed,
  PanelLeftOpen,
  PanelLeftRightDashed,
  PanelRight,
  PanelRightClose,
  PanelRightDashed,
  PanelRightOpen,
  PanelTop,
  PanelTopBottomDashed,
  PanelTopClose,
  PanelTopDashed,
  PanelTopOpen,
  PanelsLeftBottom,
  PanelsRightBottom,
  PanelsTopLeft,
  PaperBag,
  Paperclip,
  Parasol,
  Parentheses,
  ParkingMeter,
  PartyPopper,
  Pause,
  PawPrint,
  PcCase,
  Pen,
  PenLine,
  PenOff,
  PenTool,
  Pencil,
  PencilLine,
  PencilOff,
  PencilRuler,
  PencilSparkles,
  Pentagon,
  Percent,
  PersonStanding,
  Phi,
  PhilippinePeso,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  Pi,
  Piano,
  Pickaxe,
  PictureInPicture,
  PictureInPicture2,
  PiggyBank,
  Pilcrow,
  PilcrowLeft,
  PilcrowRight,
  Pill,
  PillBottle,
  Pin,
  PinOff,
  Pipette,
  Pizza,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Play,
  PlayOff,
  PlayingCard,
  PlayingCards,
  PlayingCardsFan,
  Plug,
  Plug2,
  PlugZap,
  Plus,
  PocketKnife,
  Podium,
  Pointer,
  PointerOff,
  Popcorn,
  Popsicle,
  PoundSterling,
  Power,
  PowerOff,
  Presentation,
  Printer,
  PrinterCheck,
  PrinterX,
  Projector,
  Proportions,
  Puzzle,
  Pyramid,
  QrCode,
  Quote,
  Rabbit,
  Radar,
  Radiation,
  Radical,
  Radio,
  RadioOff,
  RadioReceiver,
  RadioTower,
  Radius,
  Rainbow,
  Rat,
  Ratio,
  Receipt,
  ReceiptCent,
  ReceiptEuro,
  ReceiptIndianRupee,
  ReceiptJapaneseYen,
  ReceiptPoundSterling,
  ReceiptRussianRuble,
  ReceiptSwissFranc,
  ReceiptText,
  ReceiptTurkishLira,
  RectangleCircle,
  RectangleEllipsis,
  RectangleGoggles,
  RectangleHorizontal,
  RectangleVertical,
  Recycle,
  Redo,
  Redo2,
  RedoDot,
  RefreshCcw,
  RefreshCcwDot,
  RefreshCw,
  RefreshCwOff,
  Refrigerator,
  Regex,
  RemoveFormatting,
  Repeat,
  Repeat1,
  Repeat2,
  RepeatOff,
  Replace,
  ReplaceAll,
  Reply,
  ReplyAll,
  Rewind,
  Ribbon,
  Road,
  RobotArm,
  RobotVacuum,
  Rocket,
  RockingChair,
  RollerCoaster,
  Rose,
  Rotate3d,
  RotateCcw,
  RotateCcwClock,
  RotateCcwKey,
  RotateCcwSquare,
  RotateCw,
  RotateCwFadingClock,
  RotateCwSquare,
  Route,
  RouteOff,
  Router,
  Rows2,
  Rows3,
  Rows4,
  Rss,
  Ruler,
  RulerDimensionLine,
  RussianRuble,
  Sailboat,
  Salad,
  Sandwich,
  Satellite,
  SatelliteDish,
  SaudiRiyal,
  Save,
  SaveAll,
  SaveCheck,
  SaveOff,
  SavePen,
  SavePlus,
  Scale,
  Scale3d,
  Scaling,
  Scan,
  ScanBarcode,
  ScanBox,
  ScanEye,
  ScanFace,
  ScanHeart,
  ScanLine,
  ScanQrCode,
  ScanSearch,
  ScanSquare,
  ScanText,
  School,
  Scissors,
  ScissorsLineDashed,
  Scooter,
  ScreenShare,
  ScreenShareOff,
  Scroll,
  ScrollText,
  Search,
  SearchAlert,
  SearchCheck,
  SearchCode,
  SearchSlash,
  SearchX,
  Section,
  Send,
  SendHorizontal,
  SendToBack,
  SeparatorHorizontal,
  SeparatorVertical,
  Server,
  ServerCog,
  ServerCrash,
  ServerOff,
  ServerPlus,
  Settings,
  Settings2,
  Shapes,
  Share,
  Share2,
  Sheet,
  Shell,
  ShelvingUnit,
  Shield,
  ShieldAlert,
  ShieldBan,
  ShieldCheck,
  ShieldCog,
  ShieldCogCorner,
  ShieldEllipsis,
  ShieldHalf,
  ShieldKeyhole,
  ShieldLock,
  ShieldMinus,
  ShieldOff,
  ShieldPlus,
  ShieldQuestionMark,
  ShieldUser,
  ShieldX,
  Ship,
  ShipCargo,
  ShipWheel,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Shredder,
  Shrimp,
  Shrink,
  Shrub,
  Shuffle,
  Sigma,
  Signal,
  SignalHigh,
  SignalLow,
  SignalMedium,
  SignalZero,
  Signature,
  Signpost,
  SignpostBig,
  Siren,
  SkipBack,
  SkipForward,
  Skull,
  Slash,
  Slice,
  SlidersHorizontal,
  SlidersVertical,
  Smartphone,
  SmartphoneCharging,
  SmartphoneNfc,
  Snail,
  Snowflake,
  SoapDispenserDroplet,
  Sofa,
  SolarPanel,
  Soup,
  Space,
  Spade,
  Sparkle,
  Sparkles,
  Speaker,
  Speech,
  SpellCheck,
  SpellCheck2,
  Spline,
  SplinePointer,
  Split,
  Spool,
  SportShoe,
  Spotlight,
  SprayCan,
  Sprout,
  Square,
  SquareActivity,
  SquareArrowDown,
  SquareArrowDownLeft,
  SquareArrowDownRight,
  SquareArrowLeft,
  SquareArrowOutDownLeft,
  SquareArrowOutDownRight,
  SquareArrowOutUpLeft,
  SquareArrowOutUpRight,
  SquareArrowRight,
  SquareArrowRightEnter,
  SquareArrowRightExit,
  SquareArrowUp,
  SquareArrowUpLeft,
  SquareArrowUpRight,
  SquareAsterisk,
  SquareBottomDashedScissors,
  SquareCenterlineDashedHorizontal,
  SquareCenterlineDashedVertical,
  SquareChartGantt,
  SquareCheck,
  SquareCheckBig,
  SquareChevronDown,
  SquareChevronLeft,
  SquareChevronRight,
  SquareChevronUp,
  SquareCode,
  SquareDashed,
  SquareDashedBottom,
  SquareDashedBottomCode,
  SquareDashedKanban,
  SquareDashedMousePointer,
  SquareDashedText,
  SquareDashedTopSolid,
  SquareDimensions,
  SquareDivide,
  SquareDot,
  SquareEqual,
  SquareFunction,
  SquareKanban,
  SquareLibrary,
  SquareM,
  SquareMenu,
  SquareMinus,
  SquareMousePointer,
  SquareOff,
  SquareParking,
  SquareParkingOff,
  SquarePause,
  SquarePen,
  SquarePercent,
  SquarePi,
  SquarePilcrow,
  SquarePlay,
  SquarePlus,
  SquarePower,
  SquareRadical,
  SquareRoundCorner,
  SquareScissors,
  SquareSigma,
  SquareSlash,
  SquareSplitHorizontal,
  SquareSplitVertical,
  SquareSquare,
  SquareStack,
  SquareStar,
  SquareStop,
  SquareTerminal,
  SquareText,
  SquareUser,
  SquareUserRound,
  SquareX,
  SquaresExclude,
  SquaresIntersect,
  SquaresSubtract,
  SquaresUnite,
  Squircle,
  SquircleDashed,
  Squirrel,
  Stamp,
  Star,
  StarCheck,
  StarHalf,
  StarMinus,
  StarOff,
  StarPlus,
  StarX,
  StepBack,
  StepForward,
  Stethoscope,
  Sticker,
  StickyNote,
  StickyNoteCheck,
  StickyNoteMinus,
  StickyNoteOff,
  StickyNotePlus,
  StickyNoteX,
  StickyNotes,
  Stone,
  Store,
  StretchHorizontal,
  StretchVertical,
  Strikethrough,
  Subscript,
  Summary,
  Sun,
  SunDim,
  SunMedium,
  SunMoon,
  SunSnow,
  Sunrise,
  Sunset,
  Superscript,
  SwatchBook,
  SwissFranc,
  SwitchCamera,
  Sword,
  Swords,
  Syringe,
  Table,
  Table2,
  TableCellsMerge,
  TableCellsSplit,
  TableColumnsSplit,
  TableOfContents,
  TableProperties,
  TableRowsSplit,
  Tablet,
  TabletSmartphone,
  Tablets,
  Tag,
  TagPlus,
  TagX,
  Tags,
  Tally1,
  Tally2,
  Tally3,
  Tally4,
  Tally5,
  Tangent,
  Target,
  Telescope,
  Tent,
  TentTree,
  Terminal,
  TestTube,
  TestTubeDiagonal,
  TestTubes,
  TextAlignCenter,
  TextAlignEnd,
  TextAlignJustify,
  TextAlignStart,
  TextCursor,
  TextCursorInput,
  TextInitial,
  TextQuote,
  TextSearch,
  TextWrap,
  Theater,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  TicketCheck,
  TicketMinus,
  TicketPercent,
  TicketPlus,
  TicketSlash,
  TicketX,
  Tickets,
  TicketsPlane,
  Timeline,
  Timer,
  TimerOff,
  TimerReset,
  ToggleLeft,
  ToggleRight,
  Toilet,
  ToolCase,
  Toolbox,
  Tornado,
  Torus,
  Touchpad,
  TouchpadOff,
  TowelRack,
  TowerControl,
  ToyBrick,
  Tractor,
  TrafficCone,
  Trailer,
  TrainFront,
  TrainFrontTunnel,
  TrainTrack,
  TramFront,
  Transgender,
  Trash,
  Trash2,
  TreeDeciduous,
  TreePalm,
  TreePine,
  Trees,
  TrendingDown,
  TrendingUp,
  TrendingUpDown,
  Triangle,
  TriangleAlert,
  TriangleDashed,
  TriangleRight,
  Trophy,
  Truck,
  TruckElectric,
  TurkishLira,
  Turntable,
  Turtle,
  Tv,
  TvMinimal,
  TvMinimalPlay,
  Type,
  TypeOutline,
  Umbrella,
  UmbrellaOff,
  Underline,
  Undo,
  Undo2,
  UndoDot,
  UnfoldHorizontal,
  UnfoldVertical,
  Ungroup,
  University,
  Unlink,
  Unlink2,
  Unplug,
  Upload,
  Usb,
  UsbCPort,
  User,
  UserCheck,
  UserCog,
  UserKey,
  UserLock,
  UserMinus,
  UserPen,
  UserPlus,
  UserRound,
  UserRoundArrowLeft,
  UserRoundCheck,
  UserRoundCog,
  UserRoundKey,
  UserRoundMinus,
  UserRoundPen,
  UserRoundPlus,
  UserRoundSearch,
  UserRoundX,
  UserSearch,
  UserShield,
  UserStar,
  UserX,
  Users,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  UtilityPole,
  Van,
  Variable,
  Vault,
  VectorPolygon,
  VectorSquare,
  Vegan,
  VenetianMask,
  Venus,
  VenusAndMars,
  Vibrate,
  VibrateOff,
  Video,
  VideoOff,
  Videotape,
  View,
  Voicemail,
  Volleyball,
  Volume,
  Volume1,
  Volume2,
  VolumeOff,
  VolumeX,
  Vote,
  Wallet,
  WalletCards,
  WalletMinimal,
  Wallpaper,
  Wand,
  WandSparkles,
  Warehouse,
  WashingMachine,
  Watch,
  WavesArrowDown,
  WavesArrowUp,
  WavesHorizontal,
  WavesLadder,
  WavesVertical,
  Waypoints,
  Webcam,
  WebcamOff,
  Webhook,
  WebhookOff,
  Weight,
  WeightTilde,
  Wheat,
  WheatOff,
  Whistle,
  WholeWord,
  Wifi,
  WifiCog,
  WifiHigh,
  WifiLow,
  WifiOff,
  WifiPen,
  WifiSync,
  WifiZero,
  Wind,
  WindArrowDown,
  Wine,
  WineOff,
  Workflow,
  Worm,
  Wrench,
  WrenchOff,
  X,
  XLineTop,
  Zap,
  ZapOff,
  ZodiacAquarius,
  ZodiacAries,
  ZodiacCancer,
  ZodiacCapricorn,
  ZodiacGemini,
  ZodiacLeo,
  ZodiacLibra,
  ZodiacOphiuchus,
  ZodiacPisces,
  ZodiacSagittarius,
  ZodiacScorpio,
  ZodiacTaurus,
  ZodiacVirgo,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from "lucide-react";
import type { IconKey } from "./icon-catalog.generated";

export const ICON_COMPONENTS: Readonly<Record<IconKey, LucideIcon>> = {
  "a-arrow-down": AArrowDown,
  "a-arrow-up": AArrowUp,
  "a-large-small": ALargeSmall,
  "accessibility": Accessibility,
  "activity": Activity,
  "ad": Ad,
  "air-vent": AirVent,
  "airplay": Airplay,
  "alarm-clock": AlarmClock,
  "alarm-clock-check": AlarmClockCheck,
  "alarm-clock-minus": AlarmClockMinus,
  "alarm-clock-off": AlarmClockOff,
  "alarm-clock-plus": AlarmClockPlus,
  "alarm-smoke": AlarmSmoke,
  "album": Album,
  "align-center-horizontal": AlignCenterHorizontal,
  "align-center-vertical": AlignCenterVertical,
  "align-end-horizontal": AlignEndHorizontal,
  "align-end-vertical": AlignEndVertical,
  "align-horizontal-distribute-center": AlignHorizontalDistributeCenter,
  "align-horizontal-distribute-end": AlignHorizontalDistributeEnd,
  "align-horizontal-distribute-start": AlignHorizontalDistributeStart,
  "align-horizontal-justify-center": AlignHorizontalJustifyCenter,
  "align-horizontal-justify-end": AlignHorizontalJustifyEnd,
  "align-horizontal-justify-start": AlignHorizontalJustifyStart,
  "align-horizontal-space-around": AlignHorizontalSpaceAround,
  "align-horizontal-space-between": AlignHorizontalSpaceBetween,
  "align-start-horizontal": AlignStartHorizontal,
  "align-start-vertical": AlignStartVertical,
  "align-vertical-distribute-center": AlignVerticalDistributeCenter,
  "align-vertical-distribute-end": AlignVerticalDistributeEnd,
  "align-vertical-distribute-start": AlignVerticalDistributeStart,
  "align-vertical-justify-center": AlignVerticalJustifyCenter,
  "align-vertical-justify-end": AlignVerticalJustifyEnd,
  "align-vertical-justify-start": AlignVerticalJustifyStart,
  "align-vertical-space-around": AlignVerticalSpaceAround,
  "align-vertical-space-between": AlignVerticalSpaceBetween,
  "ambulance": Ambulance,
  "ampersand": Ampersand,
  "ampersands": Ampersands,
  "amphora": Amphora,
  "anchor": Anchor,
  "angle": Angle,
  "antenna": Antenna,
  "anvil": Anvil,
  "aperture": Aperture,
  "app-window": AppWindow,
  "app-window-mac": AppWindowMac,
  "apple": Apple,
  "archive": Archive,
  "archive-restore": ArchiveRestore,
  "archive-x": ArchiveX,
  "armchair": Armchair,
  "arrow-big-down": ArrowBigDown,
  "arrow-big-down-dash": ArrowBigDownDash,
  "arrow-big-left": ArrowBigLeft,
  "arrow-big-left-dash": ArrowBigLeftDash,
  "arrow-big-right": ArrowBigRight,
  "arrow-big-right-dash": ArrowBigRightDash,
  "arrow-big-up": ArrowBigUp,
  "arrow-big-up-dash": ArrowBigUpDash,
  "arrow-down": ArrowDown,
  "arrow-down-0-1": ArrowDown01,
  "arrow-down-1-0": ArrowDown10,
  "arrow-down-a-z": ArrowDownAZ,
  "arrow-down-from-line": ArrowDownFromLine,
  "arrow-down-left": ArrowDownLeft,
  "arrow-down-narrow-wide": ArrowDownNarrowWide,
  "arrow-down-right": ArrowDownRight,
  "arrow-down-to-dot": ArrowDownToDot,
  "arrow-down-to-line": ArrowDownToLine,
  "arrow-down-up": ArrowDownUp,
  "arrow-down-wide-narrow": ArrowDownWideNarrow,
  "arrow-down-z-a": ArrowDownZA,
  "arrow-left": ArrowLeft,
  "arrow-left-from-line": ArrowLeftFromLine,
  "arrow-left-right": ArrowLeftRight,
  "arrow-left-to-line": ArrowLeftToLine,
  "arrow-right": ArrowRight,
  "arrow-right-from-line": ArrowRightFromLine,
  "arrow-right-left": ArrowRightLeft,
  "arrow-right-to-line": ArrowRightToLine,
  "arrow-up": ArrowUp,
  "arrow-up-0-1": ArrowUp01,
  "arrow-up-1-0": ArrowUp10,
  "arrow-up-a-z": ArrowUpAZ,
  "arrow-up-down": ArrowUpDown,
  "arrow-up-from-dot": ArrowUpFromDot,
  "arrow-up-from-line": ArrowUpFromLine,
  "arrow-up-left": ArrowUpLeft,
  "arrow-up-narrow-wide": ArrowUpNarrowWide,
  "arrow-up-right": ArrowUpRight,
  "arrow-up-to-line": ArrowUpToLine,
  "arrow-up-wide-narrow": ArrowUpWideNarrow,
  "arrow-up-z-a": ArrowUpZA,
  "arrows-up-from-line": ArrowsUpFromLine,
  "asterisk": Asterisk,
  "astroid": Astroid,
  "at-sign": AtSign,
  "atom": Atom,
  "audio-lines": AudioLines,
  "audio-lines-off": AudioLinesOff,
  "audio-lines-x": AudioLinesX,
  "audio-waveform": AudioWaveform,
  "award": Award,
  "axe": Axe,
  "axis-3d": Axis3d,
  "baby": Baby,
  "backpack": Backpack,
  "badge": Badge,
  "badge-alert": BadgeAlert,
  "badge-cent": BadgeCent,
  "badge-check": BadgeCheck,
  "badge-dollar-sign": BadgeDollarSign,
  "badge-euro": BadgeEuro,
  "badge-indian-rupee": BadgeIndianRupee,
  "badge-info": BadgeInfo,
  "badge-japanese-yen": BadgeJapaneseYen,
  "badge-minus": BadgeMinus,
  "badge-percent": BadgePercent,
  "badge-plus": BadgePlus,
  "badge-pound-sterling": BadgePoundSterling,
  "badge-question-mark": BadgeQuestionMark,
  "badge-russian-ruble": BadgeRussianRuble,
  "badge-swiss-franc": BadgeSwissFranc,
  "badge-turkish-lira": BadgeTurkishLira,
  "badge-x": BadgeX,
  "baggage-claim": BaggageClaim,
  "balloon": Balloon,
  "ban": Ban,
  "banana": Banana,
  "bandage": Bandage,
  "banknote": Banknote,
  "banknote-arrow-down": BanknoteArrowDown,
  "banknote-arrow-up": BanknoteArrowUp,
  "banknote-check": BanknoteCheck,
  "banknote-x": BanknoteX,
  "barcode": Barcode,
  "barrel": Barrel,
  "baseline": Baseline,
  "bath": Bath,
  "battery": Battery,
  "battery-charging": BatteryCharging,
  "battery-full": BatteryFull,
  "battery-low": BatteryLow,
  "battery-medium": BatteryMedium,
  "battery-plus": BatteryPlus,
  "battery-warning": BatteryWarning,
  "beaker": Beaker,
  "bean": Bean,
  "bean-off": BeanOff,
  "bed": Bed,
  "bed-double": BedDouble,
  "bed-single": BedSingle,
  "beef": Beef,
  "beef-off": BeefOff,
  "beer": Beer,
  "beer-off": BeerOff,
  "bell": Bell,
  "bell-check": BellCheck,
  "bell-dot": BellDot,
  "bell-electric": BellElectric,
  "bell-minus": BellMinus,
  "bell-off": BellOff,
  "bell-plus": BellPlus,
  "bell-ring": BellRing,
  "between-horizontal-end": BetweenHorizontalEnd,
  "between-horizontal-start": BetweenHorizontalStart,
  "between-vertical-end": BetweenVerticalEnd,
  "between-vertical-start": BetweenVerticalStart,
  "biceps-flexed": BicepsFlexed,
  "bike": Bike,
  "binary": Binary,
  "binoculars": Binoculars,
  "biohazard": Biohazard,
  "bird": Bird,
  "birdhouse": Birdhouse,
  "bitcoin": Bitcoin,
  "blend": Blend,
  "blender": Blender,
  "blinds": Blinds,
  "blocks": Blocks,
  "bluetooth": Bluetooth,
  "bluetooth-connected": BluetoothConnected,
  "bluetooth-off": BluetoothOff,
  "bluetooth-searching": BluetoothSearching,
  "bold": Bold,
  "bolt": Bolt,
  "bomb": Bomb,
  "bone": Bone,
  "bone-fracture": BoneFracture,
  "book": Book,
  "book-a": BookA,
  "book-alert": BookAlert,
  "book-audio": BookAudio,
  "book-check": BookCheck,
  "book-copy": BookCopy,
  "book-dashed": BookDashed,
  "book-down": BookDown,
  "book-headphones": BookHeadphones,
  "book-heart": BookHeart,
  "book-image": BookImage,
  "book-key": BookKey,
  "book-lock": BookLock,
  "book-marked": BookMarked,
  "book-minus": BookMinus,
  "book-open": BookOpen,
  "book-open-check": BookOpenCheck,
  "book-open-text": BookOpenText,
  "book-plus": BookPlus,
  "book-search": BookSearch,
  "book-text": BookText,
  "book-type": BookType,
  "book-up": BookUp,
  "book-up-2": BookUp2,
  "book-user": BookUser,
  "book-x": BookX,
  "bookmark": Bookmark,
  "bookmark-check": BookmarkCheck,
  "bookmark-minus": BookmarkMinus,
  "bookmark-off": BookmarkOff,
  "bookmark-plus": BookmarkPlus,
  "bookmark-x": BookmarkX,
  "boom-box": BoomBox,
  "bot": Bot,
  "bot-message-square": BotMessageSquare,
  "bot-off": BotOff,
  "bottle-wine": BottleWine,
  "bow-arrow": BowArrow,
  "box": Box,
  "boxes": Boxes,
  "braces": Braces,
  "brackets": Brackets,
  "brain": Brain,
  "brain-circuit": BrainCircuit,
  "brain-cog": BrainCog,
  "brick-wall": BrickWall,
  "brick-wall-fire": BrickWallFire,
  "brick-wall-shield": BrickWallShield,
  "briefcase": Briefcase,
  "briefcase-business": BriefcaseBusiness,
  "briefcase-conveyor-belt": BriefcaseConveyorBelt,
  "briefcase-medical": BriefcaseMedical,
  "bring-to-front": BringToFront,
  "broccoli": Broccoli,
  "broom": Broom,
  "broom-sparkles": BroomSparkles,
  "brush": Brush,
  "brush-cleaning": BrushCleaning,
  "bubbles": Bubbles,
  "bug": Bug,
  "bug-off": BugOff,
  "bug-play": BugPlay,
  "building": Building,
  "building-2": Building2,
  "bus": Bus,
  "bus-front": BusFront,
  "cable": Cable,
  "cable-car": CableCar,
  "cake": Cake,
  "cake-slice": CakeSlice,
  "calculator": Calculator,
  "calendar": Calendar,
  "calendar-1": Calendar1,
  "calendar-arrow-down": CalendarArrowDown,
  "calendar-arrow-up": CalendarArrowUp,
  "calendar-check": CalendarCheck,
  "calendar-check-2": CalendarCheck2,
  "calendar-clock": CalendarClock,
  "calendar-cog": CalendarCog,
  "calendar-days": CalendarDays,
  "calendar-fold": CalendarFold,
  "calendar-heart": CalendarHeart,
  "calendar-minus": CalendarMinus,
  "calendar-minus-2": CalendarMinus2,
  "calendar-off": CalendarOff,
  "calendar-plus": CalendarPlus,
  "calendar-plus-2": CalendarPlus2,
  "calendar-range": CalendarRange,
  "calendar-search": CalendarSearch,
  "calendar-sync": CalendarSync,
  "calendar-x": CalendarX,
  "calendar-x-2": CalendarX2,
  "calendars": Calendars,
  "camera": Camera,
  "camera-off": CameraOff,
  "candy": Candy,
  "candy-cane": CandyCane,
  "candy-off": CandyOff,
  "cannabis": Cannabis,
  "cannabis-off": CannabisOff,
  "captions": Captions,
  "captions-off": CaptionsOff,
  "car": Car,
  "car-battery": CarBattery,
  "car-front": CarFront,
  "car-taxi-front": CarTaxiFront,
  "caravan": Caravan,
  "card-sim": CardSim,
  "carrot": Carrot,
  "case-lower": CaseLower,
  "case-sensitive": CaseSensitive,
  "case-upper": CaseUpper,
  "cassette-tape": CassetteTape,
  "cast": Cast,
  "castle": Castle,
  "cat": Cat,
  "cctv": Cctv,
  "cctv-off": CctvOff,
  "chart-area": ChartArea,
  "chart-bar": ChartBar,
  "chart-bar-big": ChartBarBig,
  "chart-bar-decreasing": ChartBarDecreasing,
  "chart-bar-increasing": ChartBarIncreasing,
  "chart-bar-stacked": ChartBarStacked,
  "chart-candlestick": ChartCandlestick,
  "chart-column": ChartColumn,
  "chart-column-big": ChartColumnBig,
  "chart-column-decreasing": ChartColumnDecreasing,
  "chart-column-increasing": ChartColumnIncreasing,
  "chart-column-stacked": ChartColumnStacked,
  "chart-gantt": ChartGantt,
  "chart-line": ChartLine,
  "chart-network": ChartNetwork,
  "chart-no-axes-column": ChartNoAxesColumn,
  "chart-no-axes-column-decreasing": ChartNoAxesColumnDecreasing,
  "chart-no-axes-column-increasing": ChartNoAxesColumnIncreasing,
  "chart-no-axes-combined": ChartNoAxesCombined,
  "chart-no-axes-gantt": ChartNoAxesGantt,
  "chart-pie": ChartPie,
  "chart-scatter": ChartScatter,
  "chart-spline": ChartSpline,
  "check": Check,
  "check-check": CheckCheck,
  "check-line": CheckLine,
  "chef-hat": ChefHat,
  "cherry": Cherry,
  "chess-bishop": ChessBishop,
  "chess-king": ChessKing,
  "chess-knight": ChessKnight,
  "chess-pawn": ChessPawn,
  "chess-queen": ChessQueen,
  "chess-rook": ChessRook,
  "chevron-down": ChevronDown,
  "chevron-first": ChevronFirst,
  "chevron-last": ChevronLast,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-down": ChevronsDown,
  "chevrons-down-up": ChevronsDownUp,
  "chevrons-left": ChevronsLeft,
  "chevrons-left-right": ChevronsLeftRight,
  "chevrons-left-right-ellipsis": ChevronsLeftRightEllipsis,
  "chevrons-right": ChevronsRight,
  "chevrons-right-left": ChevronsRightLeft,
  "chevrons-up": ChevronsUp,
  "chevrons-up-down": ChevronsUpDown,
  "church": Church,
  "cigarette": Cigarette,
  "cigarette-off": CigaretteOff,
  "circle": Circle,
  "circle-alert": CircleAlert,
  "circle-arrow-down": CircleArrowDown,
  "circle-arrow-left": CircleArrowLeft,
  "circle-arrow-out-down-left": CircleArrowOutDownLeft,
  "circle-arrow-out-down-right": CircleArrowOutDownRight,
  "circle-arrow-out-up-left": CircleArrowOutUpLeft,
  "circle-arrow-out-up-right": CircleArrowOutUpRight,
  "circle-arrow-right": CircleArrowRight,
  "circle-arrow-up": CircleArrowUp,
  "circle-check": CircleCheck,
  "circle-check-big": CircleCheckBig,
  "circle-chevron-down": CircleChevronDown,
  "circle-chevron-left": CircleChevronLeft,
  "circle-chevron-right": CircleChevronRight,
  "circle-chevron-up": CircleChevronUp,
  "circle-dashed": CircleDashed,
  "circle-divide": CircleDivide,
  "circle-dollar-sign": CircleDollarSign,
  "circle-dot": CircleDot,
  "circle-dot-dashed": CircleDotDashed,
  "circle-ellipsis": CircleEllipsis,
  "circle-equal": CircleEqual,
  "circle-euro": CircleEuro,
  "circle-fading-arrow-up": CircleFadingArrowUp,
  "circle-fading-plus": CircleFadingPlus,
  "circle-gauge": CircleGauge,
  "circle-minus": CircleMinus,
  "circle-off": CircleOff,
  "circle-parking": CircleParking,
  "circle-parking-off": CircleParkingOff,
  "circle-pause": CirclePause,
  "circle-percent": CirclePercent,
  "circle-pile": CirclePile,
  "circle-play": CirclePlay,
  "circle-plus": CirclePlus,
  "circle-pound-sterling": CirclePoundSterling,
  "circle-power": CirclePower,
  "circle-question-mark": CircleQuestionMark,
  "circle-slash": CircleSlash,
  "circle-slash-2": CircleSlash2,
  "circle-small": CircleSmall,
  "circle-star": CircleStar,
  "circle-stop": CircleStop,
  "circle-user": CircleUser,
  "circle-user-round": CircleUserRound,
  "circle-x": CircleX,
  "circuit-board": CircuitBoard,
  "citrus": Citrus,
  "clapperboard": Clapperboard,
  "clipboard": Clipboard,
  "clipboard-check": ClipboardCheck,
  "clipboard-clock": ClipboardClock,
  "clipboard-copy": ClipboardCopy,
  "clipboard-list": ClipboardList,
  "clipboard-minus": ClipboardMinus,
  "clipboard-paste": ClipboardPaste,
  "clipboard-pen": ClipboardPen,
  "clipboard-pen-line": ClipboardPenLine,
  "clipboard-plus": ClipboardPlus,
  "clipboard-type": ClipboardType,
  "clipboard-x": ClipboardX,
  "clock": Clock,
  "clock-1": Clock1,
  "clock-10": Clock10,
  "clock-11": Clock11,
  "clock-12": Clock12,
  "clock-2": Clock2,
  "clock-3": Clock3,
  "clock-4": Clock4,
  "clock-5": Clock5,
  "clock-6": Clock6,
  "clock-7": Clock7,
  "clock-8": Clock8,
  "clock-9": Clock9,
  "clock-alert": ClockAlert,
  "clock-arrow-down": ClockArrowDown,
  "clock-arrow-left": ClockArrowLeft,
  "clock-arrow-right": ClockArrowRight,
  "clock-arrow-up": ClockArrowUp,
  "clock-check": ClockCheck,
  "clock-fading": ClockFading,
  "clock-plus": ClockPlus,
  "closed-caption": ClosedCaption,
  "cloud": Cloud,
  "cloud-alert": CloudAlert,
  "cloud-backup": CloudBackup,
  "cloud-check": CloudCheck,
  "cloud-cog": CloudCog,
  "cloud-download": CloudDownload,
  "cloud-drizzle": CloudDrizzle,
  "cloud-fog": CloudFog,
  "cloud-hail": CloudHail,
  "cloud-lightning": CloudLightning,
  "cloud-moon": CloudMoon,
  "cloud-moon-rain": CloudMoonRain,
  "cloud-off": CloudOff,
  "cloud-rain": CloudRain,
  "cloud-rain-wind": CloudRainWind,
  "cloud-snow": CloudSnow,
  "cloud-sun": CloudSun,
  "cloud-sun-rain": CloudSunRain,
  "cloud-sync": CloudSync,
  "cloud-upload": CloudUpload,
  "cloudy": Cloudy,
  "clover": Clover,
  "club": Club,
  "code": Code,
  "code-xml": CodeXml,
  "coffee": Coffee,
  "cog": Cog,
  "coins": Coins,
  "columns-2": Columns2,
  "columns-3": Columns3,
  "columns-3-cog": Columns3Cog,
  "columns-4": Columns4,
  "combine": Combine,
  "command": Command,
  "compass": Compass,
  "component": Component,
  "computer": Computer,
  "concierge-bell": ConciergeBell,
  "cone": Cone,
  "construction": Construction,
  "contact": Contact,
  "contact-round": ContactRound,
  "container": Container,
  "contrast": Contrast,
  "cookie": Cookie,
  "cooking-pot": CookingPot,
  "copy": Copy,
  "copy-check": CopyCheck,
  "copy-minus": CopyMinus,
  "copy-plus": CopyPlus,
  "copy-slash": CopySlash,
  "copy-x": CopyX,
  "copyleft": Copyleft,
  "copyright": Copyright,
  "corner-down-left": CornerDownLeft,
  "corner-down-right": CornerDownRight,
  "corner-left-down": CornerLeftDown,
  "corner-left-up": CornerLeftUp,
  "corner-right-down": CornerRightDown,
  "corner-right-up": CornerRightUp,
  "corner-up-left": CornerUpLeft,
  "corner-up-right": CornerUpRight,
  "cpu": Cpu,
  "creative-commons": CreativeCommons,
  "credit-card": CreditCard,
  "credit-card-check": CreditCardCheck,
  "credit-card-minus": CreditCardMinus,
  "credit-card-plus": CreditCardPlus,
  "credit-card-x": CreditCardX,
  "croissant": Croissant,
  "crop": Crop,
  "cross": Cross,
  "crosshair": Crosshair,
  "crown": Crown,
  "cuboid": Cuboid,
  "cup-soda": CupSoda,
  "currency": Currency,
  "cylinder": Cylinder,
  "dam": Dam,
  "database": Database,
  "database-arrow-down": DatabaseArrowDown,
  "database-arrow-up": DatabaseArrowUp,
  "database-backup": DatabaseBackup,
  "database-check": DatabaseCheck,
  "database-minus": DatabaseMinus,
  "database-plus": DatabasePlus,
  "database-search": DatabaseSearch,
  "database-x": DatabaseX,
  "database-zap": DatabaseZap,
  "decimals-arrow-left": DecimalsArrowLeft,
  "decimals-arrow-right": DecimalsArrowRight,
  "delete": Delete,
  "dessert": Dessert,
  "diameter": Diameter,
  "diamond": Diamond,
  "diamond-minus": DiamondMinus,
  "diamond-percent": DiamondPercent,
  "diamond-plus": DiamondPlus,
  "dice-1": Dice1,
  "dice-2": Dice2,
  "dice-3": Dice3,
  "dice-4": Dice4,
  "dice-5": Dice5,
  "dice-6": Dice6,
  "dices": Dices,
  "diff": Diff,
  "disc": Disc,
  "disc-2": Disc2,
  "disc-3": Disc3,
  "disc-album": DiscAlbum,
  "divide": Divide,
  "dna": Dna,
  "dna-off": DnaOff,
  "dock": Dock,
  "dog": Dog,
  "dollar-sign": DollarSign,
  "donut": Donut,
  "door-closed": DoorClosed,
  "door-closed-locked": DoorClosedLocked,
  "door-open": DoorOpen,
  "dot": Dot,
  "download": Download,
  "drafting-compass": DraftingCompass,
  "drama": Drama,
  "drill": Drill,
  "drone": Drone,
  "droplet": Droplet,
  "droplet-off": DropletOff,
  "droplets": Droplets,
  "drum": Drum,
  "drumstick": Drumstick,
  "dumbbell": Dumbbell,
  "ear": Ear,
  "ear-off": EarOff,
  "earth": Earth,
  "earth-lock": EarthLock,
  "eclipse": Eclipse,
  "egg": Egg,
  "egg-fried": EggFried,
  "egg-off": EggOff,
  "eject": Eject,
  "ellipse": Ellipse,
  "ellipsis": Ellipsis,
  "ellipsis-vertical": EllipsisVertical,
  "equal": Equal,
  "equal-approximately": EqualApproximately,
  "equal-not": EqualNot,
  "eraser": Eraser,
  "ethernet-port": EthernetPort,
  "euro": Euro,
  "ev-charger": EvCharger,
  "expand": Expand,
  "external-link": ExternalLink,
  "eye": Eye,
  "eye-closed": EyeClosed,
  "eye-dashed": EyeDashed,
  "eye-off": EyeOff,
  "face-angry": FaceAngry,
  "face-expressionless": FaceExpressionless,
  "face-grinning": FaceGrinning,
  "face-neutral": FaceNeutral,
  "face-slightly-frowning": FaceSlightlyFrowning,
  "face-slightly-smiling": FaceSlightlySmiling,
  "face-slightly-smiling-plus": FaceSlightlySmilingPlus,
  "factory": Factory,
  "fan": Fan,
  "fast-forward": FastForward,
  "feather": Feather,
  "fence": Fence,
  "ferris-wheel": FerrisWheel,
  "file": File,
  "file-archive": FileArchive,
  "file-axis-3d": FileAxis3d,
  "file-badge": FileBadge,
  "file-box": FileBox,
  "file-braces": FileBraces,
  "file-braces-corner": FileBracesCorner,
  "file-chart-column": FileChartColumn,
  "file-chart-column-increasing": FileChartColumnIncreasing,
  "file-chart-line": FileChartLine,
  "file-chart-pie": FileChartPie,
  "file-check": FileCheck,
  "file-check-corner": FileCheckCorner,
  "file-clock": FileClock,
  "file-code": FileCode,
  "file-code-corner": FileCodeCorner,
  "file-cog": FileCog,
  "file-diff": FileDiff,
  "file-digit": FileDigit,
  "file-down": FileDown,
  "file-exclamation-point": FileExclamationPoint,
  "file-headphone": FileHeadphone,
  "file-heart": FileHeart,
  "file-image": FileImage,
  "file-input": FileInput,
  "file-key": FileKey,
  "file-lock": FileLock,
  "file-minus": FileMinus,
  "file-minus-corner": FileMinusCorner,
  "file-music": FileMusic,
  "file-output": FileOutput,
  "file-pen": FilePen,
  "file-pen-line": FilePenLine,
  "file-play": FilePlay,
  "file-plus": FilePlus,
  "file-plus-corner": FilePlusCorner,
  "file-question-mark": FileQuestionMark,
  "file-scan": FileScan,
  "file-search": FileSearch,
  "file-search-corner": FileSearchCorner,
  "file-signal": FileSignal,
  "file-sliders": FileSliders,
  "file-spreadsheet": FileSpreadsheet,
  "file-stack": FileStack,
  "file-symlink": FileSymlink,
  "file-terminal": FileTerminal,
  "file-text": FileText,
  "file-type": FileType,
  "file-type-corner": FileTypeCorner,
  "file-up": FileUp,
  "file-user": FileUser,
  "file-video-camera": FileVideoCamera,
  "file-volume": FileVolume,
  "file-x": FileX,
  "file-x-corner": FileXCorner,
  "files": Files,
  "film": Film,
  "fingerprint-pattern": FingerprintPattern,
  "fire-extinguisher": FireExtinguisher,
  "fish": Fish,
  "fish-off": FishOff,
  "fish-symbol": FishSymbol,
  "fishing-hook": FishingHook,
  "fishing-rod": FishingRod,
  "flag": Flag,
  "flag-off": FlagOff,
  "flag-triangle-left": FlagTriangleLeft,
  "flag-triangle-right": FlagTriangleRight,
  "flame": Flame,
  "flame-kindling": FlameKindling,
  "flashlight": Flashlight,
  "flashlight-off": FlashlightOff,
  "flask-conical": FlaskConical,
  "flask-conical-off": FlaskConicalOff,
  "flask-round": FlaskRound,
  "flip-horizontal-2": FlipHorizontal2,
  "flip-vertical-2": FlipVertical2,
  "flower": Flower,
  "flower-2": Flower2,
  "focus": Focus,
  "fold-horizontal": FoldHorizontal,
  "fold-vertical": FoldVertical,
  "folder": Folder,
  "folder-archive": FolderArchive,
  "folder-bookmark": FolderBookmark,
  "folder-check": FolderCheck,
  "folder-clock": FolderClock,
  "folder-closed": FolderClosed,
  "folder-code": FolderCode,
  "folder-cog": FolderCog,
  "folder-dot": FolderDot,
  "folder-down": FolderDown,
  "folder-git": FolderGit,
  "folder-git-2": FolderGit2,
  "folder-heart": FolderHeart,
  "folder-input": FolderInput,
  "folder-kanban": FolderKanban,
  "folder-key": FolderKey,
  "folder-lock": FolderLock,
  "folder-minus": FolderMinus,
  "folder-open": FolderOpen,
  "folder-open-dot": FolderOpenDot,
  "folder-output": FolderOutput,
  "folder-pen": FolderPen,
  "folder-plus": FolderPlus,
  "folder-root": FolderRoot,
  "folder-search": FolderSearch,
  "folder-search-2": FolderSearch2,
  "folder-symlink": FolderSymlink,
  "folder-sync": FolderSync,
  "folder-tree": FolderTree,
  "folder-up": FolderUp,
  "folder-x": FolderX,
  "folders": Folders,
  "footprints": Footprints,
  "forklift": Forklift,
  "form": Form,
  "forward": Forward,
  "frame": Frame,
  "fuel": Fuel,
  "fullscreen": Fullscreen,
  "funnel": Funnel,
  "funnel-plus": FunnelPlus,
  "funnel-x": FunnelX,
  "galaxy": Galaxy,
  "gallery-horizontal": GalleryHorizontal,
  "gallery-horizontal-end": GalleryHorizontalEnd,
  "gallery-thumbnails": GalleryThumbnails,
  "gallery-vertical": GalleryVertical,
  "gallery-vertical-end": GalleryVerticalEnd,
  "gamepad": Gamepad,
  "gamepad-2": Gamepad2,
  "gamepad-directional": GamepadDirectional,
  "gauge": Gauge,
  "gavel": Gavel,
  "gem": Gem,
  "georgian-lari": GeorgianLari,
  "ghost": Ghost,
  "gift": Gift,
  "git-branch": GitBranch,
  "git-branch-minus": GitBranchMinus,
  "git-branch-plus": GitBranchPlus,
  "git-commit-horizontal": GitCommitHorizontal,
  "git-commit-vertical": GitCommitVertical,
  "git-compare": GitCompare,
  "git-compare-arrows": GitCompareArrows,
  "git-fork": GitFork,
  "git-graph": GitGraph,
  "git-merge": GitMerge,
  "git-merge-conflict": GitMergeConflict,
  "git-pull-request": GitPullRequest,
  "git-pull-request-arrow": GitPullRequestArrow,
  "git-pull-request-closed": GitPullRequestClosed,
  "git-pull-request-create": GitPullRequestCreate,
  "git-pull-request-create-arrow": GitPullRequestCreateArrow,
  "git-pull-request-draft": GitPullRequestDraft,
  "glass-water": GlassWater,
  "glasses": Glasses,
  "globe": Globe,
  "globe-check": GlobeCheck,
  "globe-lock": GlobeLock,
  "globe-off": GlobeOff,
  "globe-x": GlobeX,
  "goal": Goal,
  "gpu": Gpu,
  "graduation-cap": GraduationCap,
  "grape": Grape,
  "grid-2x2": Grid2x2,
  "grid-2x2-check": Grid2x2Check,
  "grid-2x2-plus": Grid2x2Plus,
  "grid-2x2-x": Grid2x2X,
  "grid-3x2": Grid3x2,
  "grid-3x3": Grid3x3,
  "grip": Grip,
  "grip-horizontal": GripHorizontal,
  "grip-vertical": GripVertical,
  "group": Group,
  "guitar": Guitar,
  "ham": Ham,
  "hamburger": Hamburger,
  "hammer": Hammer,
  "hand": Hand,
  "hand-coins": HandCoins,
  "hand-fist": HandFist,
  "hand-grab": HandGrab,
  "hand-heart": HandHeart,
  "hand-helping": HandHelping,
  "hand-metal": HandMetal,
  "hand-platter": HandPlatter,
  "handbag": Handbag,
  "handshake": Handshake,
  "hard-drive": HardDrive,
  "hard-drive-download": HardDriveDownload,
  "hard-drive-upload": HardDriveUpload,
  "hard-hat": HardHat,
  "hash": Hash,
  "hat-glasses": HatGlasses,
  "haze": Haze,
  "hd": Hd,
  "hdmi-port": HdmiPort,
  "heading": Heading,
  "heading-1": Heading1,
  "heading-2": Heading2,
  "heading-3": Heading3,
  "heading-4": Heading4,
  "heading-5": Heading5,
  "heading-6": Heading6,
  "headphone-off": HeadphoneOff,
  "headphones": Headphones,
  "headset": Headset,
  "heart": Heart,
  "heart-crack": HeartCrack,
  "heart-handshake": HeartHandshake,
  "heart-minus": HeartMinus,
  "heart-off": HeartOff,
  "heart-plus": HeartPlus,
  "heart-pulse": HeartPulse,
  "heart-x": HeartX,
  "heater": Heater,
  "helicopter": Helicopter,
  "hexagon": Hexagon,
  "highlighter": Highlighter,
  "hop": Hop,
  "hop-off": HopOff,
  "hospital": Hospital,
  "hotel": Hotel,
  "hourglass": Hourglass,
  "house": House,
  "house-heart": HouseHeart,
  "house-plug": HousePlug,
  "house-plus": HousePlus,
  "house-wifi": HouseWifi,
  "ice-cream-bowl": IceCreamBowl,
  "ice-cream-cone": IceCreamCone,
  "id-card": IdCard,
  "id-card-lanyard": IdCardLanyard,
  "image": Image,
  "image-down": ImageDown,
  "image-minus": ImageMinus,
  "image-off": ImageOff,
  "image-play": ImagePlay,
  "image-plus": ImagePlus,
  "image-up": ImageUp,
  "image-upscale": ImageUpscale,
  "images": Images,
  "import": Import,
  "inbox": Inbox,
  "indian-rupee": IndianRupee,
  "infinity": Infinity,
  "info": Info,
  "inspection-panel": InspectionPanel,
  "italic": Italic,
  "iteration-ccw": IterationCcw,
  "iteration-cw": IterationCw,
  "japanese-yen": JapaneseYen,
  "joystick": Joystick,
  "kanban": Kanban,
  "kayak": Kayak,
  "key": Key,
  "key-round": KeyRound,
  "key-square": KeySquare,
  "keyboard": Keyboard,
  "keyboard-music": KeyboardMusic,
  "keyboard-off": KeyboardOff,
  "lamp": Lamp,
  "lamp-ceiling": LampCeiling,
  "lamp-desk": LampDesk,
  "lamp-floor": LampFloor,
  "lamp-wall-down": LampWallDown,
  "lamp-wall-up": LampWallUp,
  "land-plot": LandPlot,
  "landmark": Landmark,
  "languages": Languages,
  "laptop": Laptop,
  "laptop-minimal": LaptopMinimal,
  "laptop-minimal-check": LaptopMinimalCheck,
  "lasso": Lasso,
  "lasso-select": LassoSelect,
  "layer-arrow-down": LayerArrowDown,
  "layer-arrow-up": LayerArrowUp,
  "layers": Layers,
  "layers-2": Layers2,
  "layers-arrow-down": LayersArrowDown,
  "layers-arrow-up": LayersArrowUp,
  "layers-minus": LayersMinus,
  "layers-plus": LayersPlus,
  "layout-dashboard": LayoutDashboard,
  "layout-freeform": LayoutFreeform,
  "layout-grid": LayoutGrid,
  "layout-list": LayoutList,
  "layout-panel-left": LayoutPanelLeft,
  "layout-panel-top": LayoutPanelTop,
  "layout-template": LayoutTemplate,
  "leaf": Leaf,
  "leafy-green": LeafyGreen,
  "lectern": Lectern,
  "lens-concave": LensConcave,
  "lens-convex": LensConvex,
  "library": Library,
  "library-big": LibraryBig,
  "life-buoy": LifeBuoy,
  "ligature": Ligature,
  "lightbulb": Lightbulb,
  "lightbulb-off": LightbulbOff,
  "line-dot-right-horizontal": LineDotRightHorizontal,
  "line-squiggle": LineSquiggle,
  "line-style": LineStyle,
  "link": Link,
  "link-2": Link2,
  "link-2-off": Link2Off,
  "list": List,
  "list-check": ListCheck,
  "list-checks": ListChecks,
  "list-chevrons-down-up": ListChevronsDownUp,
  "list-chevrons-up-down": ListChevronsUpDown,
  "list-clock": ListClock,
  "list-collapse": ListCollapse,
  "list-end": ListEnd,
  "list-filter": ListFilter,
  "list-filter-plus": ListFilterPlus,
  "list-indent-decrease": ListIndentDecrease,
  "list-indent-increase": ListIndentIncrease,
  "list-minus": ListMinus,
  "list-music": ListMusic,
  "list-ordered": ListOrdered,
  "list-plus": ListPlus,
  "list-restart": ListRestart,
  "list-sort-ascending": ListSortAscending,
  "list-sort-descending": ListSortDescending,
  "list-start": ListStart,
  "list-todo": ListTodo,
  "list-tree": ListTree,
  "list-video": ListVideo,
  "list-x": ListX,
  "loader": Loader,
  "loader-circle": LoaderCircle,
  "loader-pinwheel": LoaderPinwheel,
  "locate": Locate,
  "locate-fixed": LocateFixed,
  "locate-off": LocateOff,
  "lock": Lock,
  "lock-keyhole": LockKeyhole,
  "lock-keyhole-open": LockKeyholeOpen,
  "lock-open": LockOpen,
  "log-in": LogIn,
  "log-out": LogOut,
  "logs": Logs,
  "lollipop": Lollipop,
  "luggage": Luggage,
  "magnet": Magnet,
  "mail": Mail,
  "mail-badge": MailBadge,
  "mail-check": MailCheck,
  "mail-clock": MailClock,
  "mail-minus": MailMinus,
  "mail-open": MailOpen,
  "mail-plus": MailPlus,
  "mail-question-mark": MailQuestionMark,
  "mail-search": MailSearch,
  "mail-warning": MailWarning,
  "mail-x": MailX,
  "mailbox": Mailbox,
  "mails": Mails,
  "map": Map,
  "map-minus": MapMinus,
  "map-pin": MapPin,
  "map-pin-check": MapPinCheck,
  "map-pin-check-inside": MapPinCheckInside,
  "map-pin-house": MapPinHouse,
  "map-pin-minus": MapPinMinus,
  "map-pin-minus-inside": MapPinMinusInside,
  "map-pin-off": MapPinOff,
  "map-pin-pen": MapPinPen,
  "map-pin-plus": MapPinPlus,
  "map-pin-plus-inside": MapPinPlusInside,
  "map-pin-search": MapPinSearch,
  "map-pin-x": MapPinX,
  "map-pin-x-inside": MapPinXInside,
  "map-pinned": MapPinned,
  "map-plus": MapPlus,
  "mars": Mars,
  "mars-stroke": MarsStroke,
  "martini": Martini,
  "maximize": Maximize,
  "maximize-2": Maximize2,
  "medal": Medal,
  "megaphone": Megaphone,
  "megaphone-off": MegaphoneOff,
  "memory-stick": MemoryStick,
  "menu": Menu,
  "merge": Merge,
  "message-circle": MessageCircle,
  "message-circle-check": MessageCircleCheck,
  "message-circle-code": MessageCircleCode,
  "message-circle-dashed": MessageCircleDashed,
  "message-circle-dashed-check": MessageCircleDashedCheck,
  "message-circle-heart": MessageCircleHeart,
  "message-circle-more": MessageCircleMore,
  "message-circle-off": MessageCircleOff,
  "message-circle-plus": MessageCirclePlus,
  "message-circle-question-mark": MessageCircleQuestionMark,
  "message-circle-reply": MessageCircleReply,
  "message-circle-warning": MessageCircleWarning,
  "message-circle-x": MessageCircleX,
  "message-square": MessageSquare,
  "message-square-check": MessageSquareCheck,
  "message-square-code": MessageSquareCode,
  "message-square-dashed": MessageSquareDashed,
  "message-square-diff": MessageSquareDiff,
  "message-square-dot": MessageSquareDot,
  "message-square-heart": MessageSquareHeart,
  "message-square-lock": MessageSquareLock,
  "message-square-more": MessageSquareMore,
  "message-square-off": MessageSquareOff,
  "message-square-plus": MessageSquarePlus,
  "message-square-quote": MessageSquareQuote,
  "message-square-reply": MessageSquareReply,
  "message-square-share": MessageSquareShare,
  "message-square-text": MessageSquareText,
  "message-square-warning": MessageSquareWarning,
  "message-square-x": MessageSquareX,
  "messages-square": MessagesSquare,
  "metronome": Metronome,
  "mic": Mic,
  "mic-audio-lines": MicAudioLines,
  "mic-off": MicOff,
  "mic-signal": MicSignal,
  "mic-vocal": MicVocal,
  "microchip": Microchip,
  "microscope": Microscope,
  "microwave": Microwave,
  "midi-port": MidiPort,
  "milestone": Milestone,
  "milk": Milk,
  "milk-off": MilkOff,
  "minimize": Minimize,
  "minimize-2": Minimize2,
  "minus": Minus,
  "mirror-rectangular": MirrorRectangular,
  "mirror-round": MirrorRound,
  "monitor": Monitor,
  "monitor-check": MonitorCheck,
  "monitor-cloud": MonitorCloud,
  "monitor-cog": MonitorCog,
  "monitor-dot": MonitorDot,
  "monitor-down": MonitorDown,
  "monitor-off": MonitorOff,
  "monitor-pause": MonitorPause,
  "monitor-play": MonitorPlay,
  "monitor-smartphone": MonitorSmartphone,
  "monitor-speaker": MonitorSpeaker,
  "monitor-stop": MonitorStop,
  "monitor-up": MonitorUp,
  "monitor-x": MonitorX,
  "moon": Moon,
  "moon-star": MoonStar,
  "mop": Mop,
  "mop-sparkles": MopSparkles,
  "mosque": Mosque,
  "motorbike": Motorbike,
  "mountain": Mountain,
  "mountain-snow": MountainSnow,
  "mouse": Mouse,
  "mouse-left": MouseLeft,
  "mouse-off": MouseOff,
  "mouse-pointer": MousePointer,
  "mouse-pointer-2": MousePointer2,
  "mouse-pointer-2-off": MousePointer2Off,
  "mouse-pointer-ban": MousePointerBan,
  "mouse-pointer-click": MousePointerClick,
  "mouse-right": MouseRight,
  "move": Move,
  "move-3d": Move3d,
  "move-diagonal": MoveDiagonal,
  "move-diagonal-2": MoveDiagonal2,
  "move-down": MoveDown,
  "move-down-left": MoveDownLeft,
  "move-down-right": MoveDownRight,
  "move-horizontal": MoveHorizontal,
  "move-left": MoveLeft,
  "move-right": MoveRight,
  "move-up": MoveUp,
  "move-up-left": MoveUpLeft,
  "move-up-right": MoveUpRight,
  "move-vertical": MoveVertical,
  "music": Music,
  "music-2": Music2,
  "music-3": Music3,
  "music-4": Music4,
  "navigation": Navigation,
  "navigation-2": Navigation2,
  "navigation-2-off": Navigation2Off,
  "navigation-off": NavigationOff,
  "network": Network,
  "newspaper": Newspaper,
  "nfc": Nfc,
  "non-binary": NonBinary,
  "notebook": Notebook,
  "notebook-pen": NotebookPen,
  "notebook-tabs": NotebookTabs,
  "notebook-text": NotebookText,
  "notepad-text": NotepadText,
  "notepad-text-dashed": NotepadTextDashed,
  "nut": Nut,
  "nut-off": NutOff,
  "octagon": Octagon,
  "octagon-alert": OctagonAlert,
  "octagon-minus": OctagonMinus,
  "octagon-pause": OctagonPause,
  "octagon-x": OctagonX,
  "omega": Omega,
  "option": Option,
  "orbit": Orbit,
  "origami": Origami,
  "package": Package,
  "package-2": Package2,
  "package-check": PackageCheck,
  "package-minus": PackageMinus,
  "package-open": PackageOpen,
  "package-plus": PackagePlus,
  "package-search": PackageSearch,
  "package-x": PackageX,
  "paint-bucket": PaintBucket,
  "paint-roller": PaintRoller,
  "paintbrush": Paintbrush,
  "paintbrush-vertical": PaintbrushVertical,
  "palette": Palette,
  "panda": Panda,
  "panel-bottom": PanelBottom,
  "panel-bottom-close": PanelBottomClose,
  "panel-bottom-dashed": PanelBottomDashed,
  "panel-bottom-open": PanelBottomOpen,
  "panel-left": PanelLeft,
  "panel-left-close": PanelLeftClose,
  "panel-left-dashed": PanelLeftDashed,
  "panel-left-open": PanelLeftOpen,
  "panel-left-right-dashed": PanelLeftRightDashed,
  "panel-right": PanelRight,
  "panel-right-close": PanelRightClose,
  "panel-right-dashed": PanelRightDashed,
  "panel-right-open": PanelRightOpen,
  "panel-top": PanelTop,
  "panel-top-bottom-dashed": PanelTopBottomDashed,
  "panel-top-close": PanelTopClose,
  "panel-top-dashed": PanelTopDashed,
  "panel-top-open": PanelTopOpen,
  "panels-left-bottom": PanelsLeftBottom,
  "panels-right-bottom": PanelsRightBottom,
  "panels-top-left": PanelsTopLeft,
  "paper-bag": PaperBag,
  "paperclip": Paperclip,
  "parasol": Parasol,
  "parentheses": Parentheses,
  "parking-meter": ParkingMeter,
  "party-popper": PartyPopper,
  "pause": Pause,
  "paw-print": PawPrint,
  "pc-case": PcCase,
  "pen": Pen,
  "pen-line": PenLine,
  "pen-off": PenOff,
  "pen-tool": PenTool,
  "pencil": Pencil,
  "pencil-line": PencilLine,
  "pencil-off": PencilOff,
  "pencil-ruler": PencilRuler,
  "pencil-sparkles": PencilSparkles,
  "pentagon": Pentagon,
  "percent": Percent,
  "person-standing": PersonStanding,
  "phi": Phi,
  "philippine-peso": PhilippinePeso,
  "phone": Phone,
  "phone-call": PhoneCall,
  "phone-forwarded": PhoneForwarded,
  "phone-incoming": PhoneIncoming,
  "phone-missed": PhoneMissed,
  "phone-off": PhoneOff,
  "phone-outgoing": PhoneOutgoing,
  "pi": Pi,
  "piano": Piano,
  "pickaxe": Pickaxe,
  "picture-in-picture": PictureInPicture,
  "picture-in-picture-2": PictureInPicture2,
  "piggy-bank": PiggyBank,
  "pilcrow": Pilcrow,
  "pilcrow-left": PilcrowLeft,
  "pilcrow-right": PilcrowRight,
  "pill": Pill,
  "pill-bottle": PillBottle,
  "pin": Pin,
  "pin-off": PinOff,
  "pipette": Pipette,
  "pizza": Pizza,
  "plane": Plane,
  "plane-landing": PlaneLanding,
  "plane-takeoff": PlaneTakeoff,
  "play": Play,
  "play-off": PlayOff,
  "playing-card": PlayingCard,
  "playing-cards": PlayingCards,
  "playing-cards-fan": PlayingCardsFan,
  "plug": Plug,
  "plug-2": Plug2,
  "plug-zap": PlugZap,
  "plus": Plus,
  "pocket-knife": PocketKnife,
  "podium": Podium,
  "pointer": Pointer,
  "pointer-off": PointerOff,
  "popcorn": Popcorn,
  "popsicle": Popsicle,
  "pound-sterling": PoundSterling,
  "power": Power,
  "power-off": PowerOff,
  "presentation": Presentation,
  "printer": Printer,
  "printer-check": PrinterCheck,
  "printer-x": PrinterX,
  "projector": Projector,
  "proportions": Proportions,
  "puzzle": Puzzle,
  "pyramid": Pyramid,
  "qr-code": QrCode,
  "quote": Quote,
  "rabbit": Rabbit,
  "radar": Radar,
  "radiation": Radiation,
  "radical": Radical,
  "radio": Radio,
  "radio-off": RadioOff,
  "radio-receiver": RadioReceiver,
  "radio-tower": RadioTower,
  "radius": Radius,
  "rainbow": Rainbow,
  "rat": Rat,
  "ratio": Ratio,
  "receipt": Receipt,
  "receipt-cent": ReceiptCent,
  "receipt-euro": ReceiptEuro,
  "receipt-indian-rupee": ReceiptIndianRupee,
  "receipt-japanese-yen": ReceiptJapaneseYen,
  "receipt-pound-sterling": ReceiptPoundSterling,
  "receipt-russian-ruble": ReceiptRussianRuble,
  "receipt-swiss-franc": ReceiptSwissFranc,
  "receipt-text": ReceiptText,
  "receipt-turkish-lira": ReceiptTurkishLira,
  "rectangle-circle": RectangleCircle,
  "rectangle-ellipsis": RectangleEllipsis,
  "rectangle-goggles": RectangleGoggles,
  "rectangle-horizontal": RectangleHorizontal,
  "rectangle-vertical": RectangleVertical,
  "recycle": Recycle,
  "redo": Redo,
  "redo-2": Redo2,
  "redo-dot": RedoDot,
  "refresh-ccw": RefreshCcw,
  "refresh-ccw-dot": RefreshCcwDot,
  "refresh-cw": RefreshCw,
  "refresh-cw-off": RefreshCwOff,
  "refrigerator": Refrigerator,
  "regex": Regex,
  "remove-formatting": RemoveFormatting,
  "repeat": Repeat,
  "repeat-1": Repeat1,
  "repeat-2": Repeat2,
  "repeat-off": RepeatOff,
  "replace": Replace,
  "replace-all": ReplaceAll,
  "reply": Reply,
  "reply-all": ReplyAll,
  "rewind": Rewind,
  "ribbon": Ribbon,
  "road": Road,
  "robot-arm": RobotArm,
  "robot-vacuum": RobotVacuum,
  "rocket": Rocket,
  "rocking-chair": RockingChair,
  "roller-coaster": RollerCoaster,
  "rose": Rose,
  "rotate-3d": Rotate3d,
  "rotate-ccw": RotateCcw,
  "rotate-ccw-clock": RotateCcwClock,
  "rotate-ccw-key": RotateCcwKey,
  "rotate-ccw-square": RotateCcwSquare,
  "rotate-cw": RotateCw,
  "rotate-cw-fading-clock": RotateCwFadingClock,
  "rotate-cw-square": RotateCwSquare,
  "route": Route,
  "route-off": RouteOff,
  "router": Router,
  "rows-2": Rows2,
  "rows-3": Rows3,
  "rows-4": Rows4,
  "rss": Rss,
  "ruler": Ruler,
  "ruler-dimension-line": RulerDimensionLine,
  "russian-ruble": RussianRuble,
  "sailboat": Sailboat,
  "salad": Salad,
  "sandwich": Sandwich,
  "satellite": Satellite,
  "satellite-dish": SatelliteDish,
  "saudi-riyal": SaudiRiyal,
  "save": Save,
  "save-all": SaveAll,
  "save-check": SaveCheck,
  "save-off": SaveOff,
  "save-pen": SavePen,
  "save-plus": SavePlus,
  "scale": Scale,
  "scale-3d": Scale3d,
  "scaling": Scaling,
  "scan": Scan,
  "scan-barcode": ScanBarcode,
  "scan-box": ScanBox,
  "scan-eye": ScanEye,
  "scan-face": ScanFace,
  "scan-heart": ScanHeart,
  "scan-line": ScanLine,
  "scan-qr-code": ScanQrCode,
  "scan-search": ScanSearch,
  "scan-square": ScanSquare,
  "scan-text": ScanText,
  "school": School,
  "scissors": Scissors,
  "scissors-line-dashed": ScissorsLineDashed,
  "scooter": Scooter,
  "screen-share": ScreenShare,
  "screen-share-off": ScreenShareOff,
  "scroll": Scroll,
  "scroll-text": ScrollText,
  "search": Search,
  "search-alert": SearchAlert,
  "search-check": SearchCheck,
  "search-code": SearchCode,
  "search-slash": SearchSlash,
  "search-x": SearchX,
  "section": Section,
  "send": Send,
  "send-horizontal": SendHorizontal,
  "send-to-back": SendToBack,
  "separator-horizontal": SeparatorHorizontal,
  "separator-vertical": SeparatorVertical,
  "server": Server,
  "server-cog": ServerCog,
  "server-crash": ServerCrash,
  "server-off": ServerOff,
  "server-plus": ServerPlus,
  "settings": Settings,
  "settings-2": Settings2,
  "shapes": Shapes,
  "share": Share,
  "share-2": Share2,
  "sheet": Sheet,
  "shell": Shell,
  "shelving-unit": ShelvingUnit,
  "shield": Shield,
  "shield-alert": ShieldAlert,
  "shield-ban": ShieldBan,
  "shield-check": ShieldCheck,
  "shield-cog": ShieldCog,
  "shield-cog-corner": ShieldCogCorner,
  "shield-ellipsis": ShieldEllipsis,
  "shield-half": ShieldHalf,
  "shield-keyhole": ShieldKeyhole,
  "shield-lock": ShieldLock,
  "shield-minus": ShieldMinus,
  "shield-off": ShieldOff,
  "shield-plus": ShieldPlus,
  "shield-question-mark": ShieldQuestionMark,
  "shield-user": ShieldUser,
  "shield-x": ShieldX,
  "ship": Ship,
  "ship-cargo": ShipCargo,
  "ship-wheel": ShipWheel,
  "shirt": Shirt,
  "shopping-bag": ShoppingBag,
  "shopping-basket": ShoppingBasket,
  "shopping-cart": ShoppingCart,
  "shovel": Shovel,
  "shower-head": ShowerHead,
  "shredder": Shredder,
  "shrimp": Shrimp,
  "shrink": Shrink,
  "shrub": Shrub,
  "shuffle": Shuffle,
  "sigma": Sigma,
  "signal": Signal,
  "signal-high": SignalHigh,
  "signal-low": SignalLow,
  "signal-medium": SignalMedium,
  "signal-zero": SignalZero,
  "signature": Signature,
  "signpost": Signpost,
  "signpost-big": SignpostBig,
  "siren": Siren,
  "skip-back": SkipBack,
  "skip-forward": SkipForward,
  "skull": Skull,
  "slash": Slash,
  "slice": Slice,
  "sliders-horizontal": SlidersHorizontal,
  "sliders-vertical": SlidersVertical,
  "smartphone": Smartphone,
  "smartphone-charging": SmartphoneCharging,
  "smartphone-nfc": SmartphoneNfc,
  "snail": Snail,
  "snowflake": Snowflake,
  "soap-dispenser-droplet": SoapDispenserDroplet,
  "sofa": Sofa,
  "solar-panel": SolarPanel,
  "soup": Soup,
  "space": Space,
  "spade": Spade,
  "sparkle": Sparkle,
  "sparkles": Sparkles,
  "speaker": Speaker,
  "speech": Speech,
  "spell-check": SpellCheck,
  "spell-check-2": SpellCheck2,
  "spline": Spline,
  "spline-pointer": SplinePointer,
  "split": Split,
  "spool": Spool,
  "sport-shoe": SportShoe,
  "spotlight": Spotlight,
  "spray-can": SprayCan,
  "sprout": Sprout,
  "square": Square,
  "square-activity": SquareActivity,
  "square-arrow-down": SquareArrowDown,
  "square-arrow-down-left": SquareArrowDownLeft,
  "square-arrow-down-right": SquareArrowDownRight,
  "square-arrow-left": SquareArrowLeft,
  "square-arrow-out-down-left": SquareArrowOutDownLeft,
  "square-arrow-out-down-right": SquareArrowOutDownRight,
  "square-arrow-out-up-left": SquareArrowOutUpLeft,
  "square-arrow-out-up-right": SquareArrowOutUpRight,
  "square-arrow-right": SquareArrowRight,
  "square-arrow-right-enter": SquareArrowRightEnter,
  "square-arrow-right-exit": SquareArrowRightExit,
  "square-arrow-up": SquareArrowUp,
  "square-arrow-up-left": SquareArrowUpLeft,
  "square-arrow-up-right": SquareArrowUpRight,
  "square-asterisk": SquareAsterisk,
  "square-bottom-dashed-scissors": SquareBottomDashedScissors,
  "square-centerline-dashed-horizontal": SquareCenterlineDashedHorizontal,
  "square-centerline-dashed-vertical": SquareCenterlineDashedVertical,
  "square-chart-gantt": SquareChartGantt,
  "square-check": SquareCheck,
  "square-check-big": SquareCheckBig,
  "square-chevron-down": SquareChevronDown,
  "square-chevron-left": SquareChevronLeft,
  "square-chevron-right": SquareChevronRight,
  "square-chevron-up": SquareChevronUp,
  "square-code": SquareCode,
  "square-dashed": SquareDashed,
  "square-dashed-bottom": SquareDashedBottom,
  "square-dashed-bottom-code": SquareDashedBottomCode,
  "square-dashed-kanban": SquareDashedKanban,
  "square-dashed-mouse-pointer": SquareDashedMousePointer,
  "square-dashed-text": SquareDashedText,
  "square-dashed-top-solid": SquareDashedTopSolid,
  "square-dimensions": SquareDimensions,
  "square-divide": SquareDivide,
  "square-dot": SquareDot,
  "square-equal": SquareEqual,
  "square-function": SquareFunction,
  "square-kanban": SquareKanban,
  "square-library": SquareLibrary,
  "square-m": SquareM,
  "square-menu": SquareMenu,
  "square-minus": SquareMinus,
  "square-mouse-pointer": SquareMousePointer,
  "square-off": SquareOff,
  "square-parking": SquareParking,
  "square-parking-off": SquareParkingOff,
  "square-pause": SquarePause,
  "square-pen": SquarePen,
  "square-percent": SquarePercent,
  "square-pi": SquarePi,
  "square-pilcrow": SquarePilcrow,
  "square-play": SquarePlay,
  "square-plus": SquarePlus,
  "square-power": SquarePower,
  "square-radical": SquareRadical,
  "square-round-corner": SquareRoundCorner,
  "square-scissors": SquareScissors,
  "square-sigma": SquareSigma,
  "square-slash": SquareSlash,
  "square-split-horizontal": SquareSplitHorizontal,
  "square-split-vertical": SquareSplitVertical,
  "square-square": SquareSquare,
  "square-stack": SquareStack,
  "square-star": SquareStar,
  "square-stop": SquareStop,
  "square-terminal": SquareTerminal,
  "square-text": SquareText,
  "square-user": SquareUser,
  "square-user-round": SquareUserRound,
  "square-x": SquareX,
  "squares-exclude": SquaresExclude,
  "squares-intersect": SquaresIntersect,
  "squares-subtract": SquaresSubtract,
  "squares-unite": SquaresUnite,
  "squircle": Squircle,
  "squircle-dashed": SquircleDashed,
  "squirrel": Squirrel,
  "stamp": Stamp,
  "star": Star,
  "star-check": StarCheck,
  "star-half": StarHalf,
  "star-minus": StarMinus,
  "star-off": StarOff,
  "star-plus": StarPlus,
  "star-x": StarX,
  "step-back": StepBack,
  "step-forward": StepForward,
  "stethoscope": Stethoscope,
  "sticker": Sticker,
  "sticky-note": StickyNote,
  "sticky-note-check": StickyNoteCheck,
  "sticky-note-minus": StickyNoteMinus,
  "sticky-note-off": StickyNoteOff,
  "sticky-note-plus": StickyNotePlus,
  "sticky-note-x": StickyNoteX,
  "sticky-notes": StickyNotes,
  "stone": Stone,
  "store": Store,
  "stretch-horizontal": StretchHorizontal,
  "stretch-vertical": StretchVertical,
  "strikethrough": Strikethrough,
  "subscript": Subscript,
  "summary": Summary,
  "sun": Sun,
  "sun-dim": SunDim,
  "sun-medium": SunMedium,
  "sun-moon": SunMoon,
  "sun-snow": SunSnow,
  "sunrise": Sunrise,
  "sunset": Sunset,
  "superscript": Superscript,
  "swatch-book": SwatchBook,
  "swiss-franc": SwissFranc,
  "switch-camera": SwitchCamera,
  "sword": Sword,
  "swords": Swords,
  "syringe": Syringe,
  "table": Table,
  "table-2": Table2,
  "table-cells-merge": TableCellsMerge,
  "table-cells-split": TableCellsSplit,
  "table-columns-split": TableColumnsSplit,
  "table-of-contents": TableOfContents,
  "table-properties": TableProperties,
  "table-rows-split": TableRowsSplit,
  "tablet": Tablet,
  "tablet-smartphone": TabletSmartphone,
  "tablets": Tablets,
  "tag": Tag,
  "tag-plus": TagPlus,
  "tag-x": TagX,
  "tags": Tags,
  "tally-1": Tally1,
  "tally-2": Tally2,
  "tally-3": Tally3,
  "tally-4": Tally4,
  "tally-5": Tally5,
  "tangent": Tangent,
  "target": Target,
  "telescope": Telescope,
  "tent": Tent,
  "tent-tree": TentTree,
  "terminal": Terminal,
  "test-tube": TestTube,
  "test-tube-diagonal": TestTubeDiagonal,
  "test-tubes": TestTubes,
  "text-align-center": TextAlignCenter,
  "text-align-end": TextAlignEnd,
  "text-align-justify": TextAlignJustify,
  "text-align-start": TextAlignStart,
  "text-cursor": TextCursor,
  "text-cursor-input": TextCursorInput,
  "text-initial": TextInitial,
  "text-quote": TextQuote,
  "text-search": TextSearch,
  "text-wrap": TextWrap,
  "theater": Theater,
  "thermometer": Thermometer,
  "thermometer-snowflake": ThermometerSnowflake,
  "thermometer-sun": ThermometerSun,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  "ticket": Ticket,
  "ticket-check": TicketCheck,
  "ticket-minus": TicketMinus,
  "ticket-percent": TicketPercent,
  "ticket-plus": TicketPlus,
  "ticket-slash": TicketSlash,
  "ticket-x": TicketX,
  "tickets": Tickets,
  "tickets-plane": TicketsPlane,
  "timeline": Timeline,
  "timer": Timer,
  "timer-off": TimerOff,
  "timer-reset": TimerReset,
  "toggle-left": ToggleLeft,
  "toggle-right": ToggleRight,
  "toilet": Toilet,
  "tool-case": ToolCase,
  "toolbox": Toolbox,
  "tornado": Tornado,
  "torus": Torus,
  "touchpad": Touchpad,
  "touchpad-off": TouchpadOff,
  "towel-rack": TowelRack,
  "tower-control": TowerControl,
  "toy-brick": ToyBrick,
  "tractor": Tractor,
  "traffic-cone": TrafficCone,
  "trailer": Trailer,
  "train-front": TrainFront,
  "train-front-tunnel": TrainFrontTunnel,
  "train-track": TrainTrack,
  "tram-front": TramFront,
  "transgender": Transgender,
  "trash": Trash,
  "trash-2": Trash2,
  "tree-deciduous": TreeDeciduous,
  "tree-palm": TreePalm,
  "tree-pine": TreePine,
  "trees": Trees,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  "trending-up-down": TrendingUpDown,
  "triangle": Triangle,
  "triangle-alert": TriangleAlert,
  "triangle-dashed": TriangleDashed,
  "triangle-right": TriangleRight,
  "trophy": Trophy,
  "truck": Truck,
  "truck-electric": TruckElectric,
  "turkish-lira": TurkishLira,
  "turntable": Turntable,
  "turtle": Turtle,
  "tv": Tv,
  "tv-minimal": TvMinimal,
  "tv-minimal-play": TvMinimalPlay,
  "type": Type,
  "type-outline": TypeOutline,
  "umbrella": Umbrella,
  "umbrella-off": UmbrellaOff,
  "underline": Underline,
  "undo": Undo,
  "undo-2": Undo2,
  "undo-dot": UndoDot,
  "unfold-horizontal": UnfoldHorizontal,
  "unfold-vertical": UnfoldVertical,
  "ungroup": Ungroup,
  "university": University,
  "unlink": Unlink,
  "unlink-2": Unlink2,
  "unplug": Unplug,
  "upload": Upload,
  "usb": Usb,
  "usb-c-port": UsbCPort,
  "user": User,
  "user-check": UserCheck,
  "user-cog": UserCog,
  "user-key": UserKey,
  "user-lock": UserLock,
  "user-minus": UserMinus,
  "user-pen": UserPen,
  "user-plus": UserPlus,
  "user-round": UserRound,
  "user-round-arrow-left": UserRoundArrowLeft,
  "user-round-check": UserRoundCheck,
  "user-round-cog": UserRoundCog,
  "user-round-key": UserRoundKey,
  "user-round-minus": UserRoundMinus,
  "user-round-pen": UserRoundPen,
  "user-round-plus": UserRoundPlus,
  "user-round-search": UserRoundSearch,
  "user-round-x": UserRoundX,
  "user-search": UserSearch,
  "user-shield": UserShield,
  "user-star": UserStar,
  "user-x": UserX,
  "users": Users,
  "users-round": UsersRound,
  "utensils": Utensils,
  "utensils-crossed": UtensilsCrossed,
  "utility-pole": UtilityPole,
  "van": Van,
  "variable": Variable,
  "vault": Vault,
  "vector-polygon": VectorPolygon,
  "vector-square": VectorSquare,
  "vegan": Vegan,
  "venetian-mask": VenetianMask,
  "venus": Venus,
  "venus-and-mars": VenusAndMars,
  "vibrate": Vibrate,
  "vibrate-off": VibrateOff,
  "video": Video,
  "video-off": VideoOff,
  "videotape": Videotape,
  "view": View,
  "voicemail": Voicemail,
  "volleyball": Volleyball,
  "volume": Volume,
  "volume-1": Volume1,
  "volume-2": Volume2,
  "volume-off": VolumeOff,
  "volume-x": VolumeX,
  "vote": Vote,
  "wallet": Wallet,
  "wallet-cards": WalletCards,
  "wallet-minimal": WalletMinimal,
  "wallpaper": Wallpaper,
  "wand": Wand,
  "wand-sparkles": WandSparkles,
  "warehouse": Warehouse,
  "washing-machine": WashingMachine,
  "watch": Watch,
  "waves-arrow-down": WavesArrowDown,
  "waves-arrow-up": WavesArrowUp,
  "waves-horizontal": WavesHorizontal,
  "waves-ladder": WavesLadder,
  "waves-vertical": WavesVertical,
  "waypoints": Waypoints,
  "webcam": Webcam,
  "webcam-off": WebcamOff,
  "webhook": Webhook,
  "webhook-off": WebhookOff,
  "weight": Weight,
  "weight-tilde": WeightTilde,
  "wheat": Wheat,
  "wheat-off": WheatOff,
  "whistle": Whistle,
  "whole-word": WholeWord,
  "wifi": Wifi,
  "wifi-cog": WifiCog,
  "wifi-high": WifiHigh,
  "wifi-low": WifiLow,
  "wifi-off": WifiOff,
  "wifi-pen": WifiPen,
  "wifi-sync": WifiSync,
  "wifi-zero": WifiZero,
  "wind": Wind,
  "wind-arrow-down": WindArrowDown,
  "wine": Wine,
  "wine-off": WineOff,
  "workflow": Workflow,
  "worm": Worm,
  "wrench": Wrench,
  "wrench-off": WrenchOff,
  "x": X,
  "x-line-top": XLineTop,
  "zap": Zap,
  "zap-off": ZapOff,
  "zodiac-aquarius": ZodiacAquarius,
  "zodiac-aries": ZodiacAries,
  "zodiac-cancer": ZodiacCancer,
  "zodiac-capricorn": ZodiacCapricorn,
  "zodiac-gemini": ZodiacGemini,
  "zodiac-leo": ZodiacLeo,
  "zodiac-libra": ZodiacLibra,
  "zodiac-ophiuchus": ZodiacOphiuchus,
  "zodiac-pisces": ZodiacPisces,
  "zodiac-sagittarius": ZodiacSagittarius,
  "zodiac-scorpio": ZodiacScorpio,
  "zodiac-taurus": ZodiacTaurus,
  "zodiac-virgo": ZodiacVirgo,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
};
